export const MOCK_PRODUCTS = [
  {
    id: "mock-1",
    title: "CyberBass ANC Wireless Earbuds with Touch Display Case",
    slug: "cyberbass-anc-wireless-earbuds",
    description: "Futuristic true wireless earbuds with active noise cancellation, low-latency gaming mode, and a high-definition color touch LCD built into the smart charging case. Control volume, track selection, and equalizer presets directly from your case!",
    category: "Audio",
    sellingPriceLkr: 8950,
    costPriceLkr: 4200,
    sku: "AUD-CYB-001",
    stock: 45,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Bluetooth Version": "5.3 Dual-Mode",
      "Active Noise Cancellation": "Up to -35dB",
      "Battery Life": "8 hrs earbuds + 32 hrs case",
      "Display": "1.47-inch TFT Touchscreen",
    }),
    supplierLink: "https://supplier.com/product/cyberbass-touch-case",
    supplierNotes: "Fast dispatch via Express Shipping.",
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 38,
  },
  {
    id: "mock-2",
    title: "Transparent TWS Gaming Earbuds 45ms Low Latency & Cyber LED",
    slug: "transparent-tws-gaming-earbuds-45ms",
    description: "Transparent mechanical-casing wireless earbuds designed for mobile gamers. Features 45ms ultra-low audio latency, 13mm titanium drivers, breathing neon RGB lights, and ENC dual microphone crystal clear voice chat.",
    category: "Audio",
    sellingPriceLkr: 6450,
    costPriceLkr: 2900,
    sku: "AUD-TRN-002",
    stock: 60,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590658006821-04f4008d5717?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Latency": "45ms Ultra-Low Gaming Mode",
      "Driver Unit": "13mm Dynamic Titanium Diaphragm",
      "Battery Life": "6 Hours + 24 Hours Charging Case",
    }),
    supplierLink: "https://supplier.com/product/transparent-gaming-tws",
    supplierNotes: "Best seller among PUBG & FreeFire players.",
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 42,
  },
  {
    id: "mock-3",
    title: "Ultra Titanium AMOLED Smartwatch with BT Calling & GPS",
    slug: "ultra-titanium-amoled-smartwatch",
    description: "Rugged aerospace-grade titanium alloy smartwatch featuring a 2.04-inch 60Hz Retina AMOLED display, standalone GPS tracking, Bluetooth HD phone calling, compass, and multi-sport tracking modes.",
    category: "Smartwatches",
    sellingPriceLkr: 14500,
    costPriceLkr: 7800,
    sku: "SW-ULT-008",
    stock: 28,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Display": "2.04-inch HD AMOLED 466x466",
      "Body Material": "Titanium Alloy & Sapphire Glass",
      "Battery": "450mAh (7-10 Days Heavy Use)",
    }),
    supplierLink: "https://supplier.com/item/ultra-titanium-watch",
    supplierNotes: "High conversion product on Facebook Video Ads.",
    isFeatured: true,
    isBestSeller: true,
    rating: 5.0,
    reviewCount: 29,
  },
  {
    id: "mock-4",
    title: "Apex Pro Mini Pocket 4G Smartphone 3-Inch Display",
    slug: "apex-pro-mini-pocket-4g-smartphone",
    description: "Ultra-compact miniature 4G Android smartphone featuring a 3.0-inch touchscreen, dual SIM standby, quad-core processor, 5MP camera, and full Google Play Store access for WhatsApp, YouTube, and banking apps.",
    category: "Smartphones",
    sellingPriceLkr: 22500,
    costPriceLkr: 12500,
    sku: "MOB-MINI-023",
    stock: 10,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Screen": "3.0-inch IPS FWVGA Touchscreen",
      "OS": "Android 12",
      "Memory": "4GB RAM + 64GB Storage",
    }),
    supplierLink: "https://supplier.com/item/mini-smartphone-4g",
    supplierNotes: "Extremely popular gadget for tech enthusiasts.",
    isFeatured: true,
    isBestSeller: false,
    rating: 4.7,
    reviewCount: 19,
  },
  {
    id: "mock-5",
    title: "Rugged IP68 Outdoor Smartphone 10600mAh Monster Battery",
    slug: "rugged-ip68-outdoor-smartphone-10600mAh",
    description: "Heavy-duty shockproof, dustproof, and 50m waterproof outdoor Android smartphone powered by a massive 10600mAh battery (up to 30 days standby), 48MP AI camera, and super loud 3.5W speaker.",
    category: "Smartphones",
    sellingPriceLkr: 34500,
    costPriceLkr: 19500,
    sku: "MOB-RUG-024",
    stock: 8,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1574944985070-8f30c4397e30?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Battery": "10600mAh with 33W Fast Charging",
      "Durability": "IP68 / IP69K Certified",
      "Memory": "8GB RAM + 256GB Storage",
    }),
    supplierLink: "https://supplier.com/product/rugged-outdoor-phone",
    supplierNotes: "High ticket item.",
    isFeatured: true,
    isBestSeller: false,
    rating: 4.9,
    reviewCount: 15,
  },
  {
    id: "mock-6",
    title: "MagSafe Magnetic Power Bank 10000mAh with Foldable Metal Stand",
    slug: "magsafe-magnetic-power-bank-10000mAh",
    description: "Ultra-slim 22.5W fast charging magnetic wireless power bank with 10000mAh battery capacity, LED digital battery percentage readout, foldable zinc alloy phone kickstand, and Type-C 20W PD input/output.",
    category: "Smartphones",
    sellingPriceLkr: 7850,
    costPriceLkr: 3600,
    sku: "MOB-PW-025",
    stock: 50,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1609592424109-dd9892f1b177?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1622445268465-843d3128919d?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Capacity": "10000mAh (3.7V / 37Wh)",
      "Wireless Power": "15W MagSafe Fast Charge",
    }),
    supplierLink: "https://supplier.com/product/10000mah-magsafe-powerbank",
    supplierNotes: "Compatible with iPhone 12/13/14/15/16 and Qi devices.",
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 54,
  },
  {
    id: "mock-7",
    title: "15W MagSafe Automatic Clamping Car Mount & Wireless Charger",
    slug: "15w-magsafe-car-mount-charger",
    description: "Smart infrared sensor automatic clamping car phone holder with 15W MagSafe wireless fast charging, 360-degree rotation ball joint, and secure air vent twist lock hook.",
    category: "Car Gadgets",
    sellingPriceLkr: 4850,
    costPriceLkr: 2100,
    sku: "CAR-MAG-013",
    stock: 50,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1586105251261-72a756497a11?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616440342232-1594ad5ec62e?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Output Power": "15W / 10W / 7.5W / 5W",
      "Clamping Mechanism": "Automatic Electric Induction",
    }),
    supplierLink: "https://supplier.com/product/auto-clamp-magsafe-mount",
    supplierNotes: "Best seller item.",
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 61,
  },
  {
    id: "mock-8",
    title: "Portable Smart Digital Tire Inflator & 6000mAh Power Bank",
    slug: "portable-smart-digital-tire-inflator",
    description: "Cordless high-speed electric air pump for car, motorcycle, and bicycle tires with preset pressure automatic shutoff, digital LCD pressure readout, emergency LED torch light, and USB power bank port.",
    category: "Car Gadgets",
    sellingPriceLkr: 7950,
    costPriceLkr: 3800,
    sku: "CAR-PUMP-014",
    stock: 35,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558981806-ec527fa84c39?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Max Pressure": "150 PSI (10.3 Bar)",
      "Inflation Speed": "35L / min",
    }),
    supplierLink: "https://supplier.com/product/smart-tire-inflator",
    supplierNotes: "High demand product.",
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 33,
  },
];
