const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const mockProducts = [
  // --- AUDIO CATEGORY ---
  {
    title: "CyberBass ANC Wireless Earbuds with Touch Display Case",
    slug: "cyberbass-anc-wireless-earbuds",
    description: "Futuristic true wireless earbuds with active noise cancellation, low-latency gaming mode, and a high-definition color touch LCD built into the smart charging case. Control volume, track selection, and equalizer presets directly from your case!",
    category: "Audio",
    sellingPriceLkr: 8950,
    costPriceLkr: 4200,
    sku: "AUD-CYB-001",
    stock: 45,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Bluetooth Version": "5.3 Dual-Mode",
      "Active Noise Cancellation": "Up to -35dB",
      "Battery Life": "8 hrs earbuds + 32 hrs case",
      "Display": "1.47-inch TFT Touchscreen",
      "Water Resistance": "IPX5 Splashproof",
    }),
    supplierLink: "https://supplier.com/product/cyberbass-touch-case",
    supplierNotes: "Fast dispatch via Express Shipping.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Transparent TWS Gaming Earbuds 45ms Low Latency & Cyber LED",
    slug: "transparent-tws-gaming-earbuds-45ms",
    description: "Transparent mechanical-casing wireless earbuds designed for mobile gamers. Features 45ms ultra-low audio latency, 13mm titanium drivers, breathing neon RGB lights, and ENC dual microphone crystal clear voice chat.",
    category: "Audio",
    sellingPriceLkr: 6450,
    costPriceLkr: 2900,
    sku: "AUD-TRN-002",
    stock: 60,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Latency": "45ms Ultra-Low Gaming Mode",
      "Driver Unit": "13mm Dynamic Titanium Diaphragm",
      "Battery Life": "6 Hours + 24 Hours Charging Case",
      "Microphone": "ENC Dual Mic Noise Cancellation",
    }),
    supplierLink: "https://supplier.com/product/transparent-gaming-tws",
    supplierNotes: "Best seller among PUBG & FreeFire players.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Bone Conduction Open-Ear Sports Headset IPX8 Waterproof",
    slug: "bone-conduction-sports-headset-ipx8",
    description: "Next-gen bone conduction headphones transmitting sound through cheekbones. Features IPX8 100% waterproof rating for swimming, built-in 32GB MP3 storage mode, and 10 hours continuous playtime.",
    category: "Audio",
    sellingPriceLkr: 11200,
    costPriceLkr: 5300,
    sku: "AUD-BONE-003",
    stock: 22,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Technology": "9th Gen Bone Conduction Transducer",
      "Waterproof Level": "IPX8 Swim-Ready (Up to 3m depth)",
      "Internal Storage": "32GB (Holds ~8,000 MP3 songs)",
      "Playtime": "10 Hours @ 70% Volume",
    }),
    supplierLink: "https://supplier.com/product/bone-conduction-ipx8",
    supplierNotes: "Comes with earplugs and swim clip strap.",
    isFeatured: false,
    isBestSeller: false,
  },
  {
    title: "Dual-Receiver Wireless Clip-on Microphone for Type-C & iPhone",
    slug: "dual-receiver-wireless-clip-on-microphone",
    description: "Plug-and-play 2.4GHz wireless lapel microphone system with intelligent AI noise reduction, 20m transmission range, and dual transmitters for vlogging, TikTok live streaming, and interview recording.",
    category: "Audio",
    sellingPriceLkr: 6450,
    costPriceLkr: 2900,
    sku: "AUD-MIC-004",
    stock: 40,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Frequency": "2.4GHz Digital Wireless",
      "Range": "20 Meters Unobstructed",
      "Latency": "Ultra-Low 0.009s",
      "Connectors": "Lightning & USB Type-C Dual Receiver",
    }),
    supplierLink: "https://supplier.com/product/wireless-mic-dual",
    supplierNotes: "Popular among Sri Lankan content creators.",
    isFeatured: false,
    isBestSeller: true,
  },
  {
    title: "Studio Pro Over-Ear ANC Headphones with 60H Playtime",
    slug: "studio-pro-over-ear-anc-headphones",
    description: "Premium high-fidelity wireless over-ear headphones featuring custom 40mm silk diaphragm drivers, hybrid active noise canceling (-38dB), transparency mode, and ultra-soft memory foam earcups.",
    category: "Audio",
    sellingPriceLkr: 12800,
    costPriceLkr: 5900,
    sku: "AUD-HD-005",
    stock: 15,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Drivers": "40mm Silk-Diaphragm Dynamic",
      "ANC Mode": "Hybrid Active Noise Cancelling",
      "Playtime": "60 Hours ANC Off / 40 Hours ANC On",
    }),
    supplierLink: "https://supplier.com/product/anc-studio-headphones",
    supplierNotes: "Includes hard shell travel case.",
    isFeatured: false,
    isBestSeller: true,
  },
  {
    title: "RGB Gaming Desktop Soundbar Bluetooth 5.3 & AUX",
    slug: "rgb-gaming-desktop-soundbar-bluetooth",
    description: "Dual dynamic driver PC soundbar with 360-degree surround sound, touch-controlled dynamic RGB lighting modes, volume knob wheel, and Bluetooth 5.3 + 3.5mm AUX dual connectivity.",
    category: "Audio",
    sellingPriceLkr: 7400,
    costPriceLkr: 3200,
    sku: "AUD-SPK-006",
    stock: 20,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Power Output": "10W Peak Audio Power",
      "RGB Lights": "6 Dynamic Lighting Modes",
      "Input": "Bluetooth 5.3 / 3.5mm AUX / USB Power",
    }),
    supplierLink: "https://supplier.com/product/rgb-pc-soundbar",
    supplierNotes: "Fits under desktop monitors perfectly.",
    isFeatured: false,
    isBestSeller: false,
  },
  {
    title: "Rugged Outdoor Waterproof Bluetooth Speaker 20W Dynamic Bass",
    slug: "rugged-outdoor-waterproof-bluetooth-speaker",
    description: "Heavy-duty IPX7 waterproof portable Bluetooth speaker with dual passive radiators for deep punchy bass, 15-hour battery life, shoulder carry strap, and built-in handsfree speakerphone.",
    category: "Audio",
    sellingPriceLkr: 8900,
    costPriceLkr: 4100,
    sku: "AUD-SPK-007",
    stock: 35,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Audio Power": "20W RMS Dual Drivers",
      "Battery": "4000mAh (15 Hours Playtime)",
      "Protection": "IPX7 Waterproof & Drop-Proof Rubberized Armor",
    }),
    supplierLink: "https://supplier.com/product/outdoor-speaker-20w",
    supplierNotes: "Ideal for beach trips and camping in Sri Lanka.",
    isFeatured: true,
    isBestSeller: false,
  },

  // --- SMARTWATCHES CATEGORY ---
  {
    title: "Ultra Titanium AMOLED Smartwatch with BT Calling & GPS",
    slug: "ultra-titanium-amoled-smartwatch",
    description: "Rugged aerospace-grade titanium alloy smartwatch featuring a 2.04-inch 60Hz Retina AMOLED display, standalone GPS tracking, Bluetooth HD phone calling, compass, and multi-sport tracking modes.",
    category: "Smartwatches",
    sellingPriceLkr: 14500,
    costPriceLkr: 7800,
    sku: "SW-ULT-008",
    stock: 28,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Display": "2.04-inch HD AMOLED 466x466",
      "Body Material": "Titanium Alloy & Sapphire Glass",
      "Battery": "450mAh (7-10 Days Heavy Use)",
      "Sensors": "SpO2, Heart Rate, ECG, Barometer",
      "Calling": "Dual Mic HD Voice Calling",
    }),
    supplierLink: "https://supplier.com/item/ultra-titanium-watch",
    supplierNotes: "High conversion product on Facebook Video Ads.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Curved AMOLED Fitness Smart Band with 24/7 Heart Rate & SpO2",
    slug: "curved-amoled-fitness-smart-band",
    description: "Ultra-lightweight sleek activity tracker with 1.47-inch 2.5D curved glass AMOLED display, 120+ exercise modes, female health tracking, blood oxygen SpO2 monitoring, and 14 days battery life.",
    category: "Smartwatches",
    sellingPriceLkr: 8200,
    costPriceLkr: 3900,
    sku: "SW-BND-009",
    stock: 30,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Display": "1.47-inch AMOLED Color Screen",
      "Water Resistance": "5ATM (50 Meters Swim-Proof)",
      "Battery Life": "Up to 14 Days Typical Use",
    }),
    supplierLink: "https://supplier.com/product/amoled-smart-band",
    supplierNotes: "Comes in Black, Navy Blue, and Rose Pink straps.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Cyberpunk Skeleton Dial Smartwatch with Rotary Crown & Steel Strap",
    slug: "cyberpunk-skeleton-dial-smartwatch",
    description: "Luxury mechanical skeleton dial smartwatch featuring a high-res IPS display, rotating encoder crown navigation, stainless steel mesh strap, Bluetooth calling, and custom watch face maker.",
    category: "Smartwatches",
    sellingPriceLkr: 16900,
    costPriceLkr: 8500,
    sku: "SW-SKL-010",
    stock: 18,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Strap": "Solid Stainless Steel + Extra Silicone Sport Strap",
      "Screen": "1.52-inch Full Circle HD Screen",
      "Functions": "NFC Door Access, BT Calling, Heart Monitor",
    }),
    supplierLink: "https://supplier.com/product/cyberpunk-skeleton-watch",
    supplierNotes: "Includes gift box and strap adjustment tool.",
    isFeatured: false,
    isBestSeller: true,
  },
  {
    title: "KidSafe GPS 4G Smartwatch with HD Video Call & SOS Button",
    slug: "kidsafe-gps-4g-smartwatch",
    description: "Waterproof children's smartwatch equipped with real-time 4G GPS+WiFi tracking, HD front video call camera, emergency SOS quick dial button, geo-fencing safety zones, and class mode.",
    category: "Smartwatches",
    sellingPriceLkr: 11800,
    costPriceLkr: 5600,
    sku: "SW-KID-011",
    stock: 25,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Location": "4G LBS + GPS + WiFi Triple Positioning",
      "Camera": "HD Wide Angle Front Camera",
      "Features": "SOS One-Key Call, Remote Voice Monitor, IP67 Waterproof",
    }),
    supplierLink: "https://supplier.com/product/kidsafe-4g-watch",
    supplierNotes: "Works with Mobitel, Dialog & Hutch SIM cards.",
    isFeatured: true,
    isBestSeller: false,
  },

  // --- CAR GADGETS CATEGORY ---
  {
    title: "4K Dual-Lens AI Car Dashcam with Night Vision & WiFi",
    slug: "4k-dual-lens-ai-car-dashcam",
    description: "Ultra HD 4K front and 1080P rear dual car camera equipped with Sony STARVIS 2 sensor, built-in G-Sensor, GPS logger, 24-hour parking monitor mode, and mobile app instant WiFi video download.",
    category: "Car Gadgets",
    sellingPriceLkr: 18900,
    costPriceLkr: 9500,
    sku: "CAR-DASH-012",
    stock: 18,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508974239320-0a029497e820?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Resolution": "Front 4K (2160P) + Rear 1080P",
      "Sensor": "Sony STARVIS IMX415",
      "Field of View": "170 Wide Angle",
      "Connectivity": "5GHz High-Speed WiFi",
      "Storage": "Supports up to 256GB MicroSD",
    }),
    supplierLink: "https://supplier.com/product/4k-dashcam-wifi",
    supplierNotes: "Includes 64GB Kingston C10 SD card.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "15W MagSafe Automatic Clamping Car Mount & Wireless Charger",
    slug: "15w-magsafe-car-mount-charger",
    description: "Smart infrared sensor automatic clamping car phone holder with 15W MagSafe wireless fast charging, 360-degree rotation ball joint, and secure air vent twist lock hook.",
    category: "Car Gadgets",
    sellingPriceLkr: 4850,
    costPriceLkr: 2100,
    sku: "CAR-MAG-013",
    stock: 50,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1586105251261-72a756497a11?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1616440342232-1594ad5ec62e?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Output Power": "15W / 10W / 7.5W / 5W",
      "Clamping Mechanism": "Automatic Electric Induction",
      "Input Interface": "USB Type-C",
      "Compatibility": "Universal (iPhone MagSafe & Android Qi)",
    }),
    supplierLink: "https://supplier.com/product/auto-clamp-magsafe-mount",
    supplierNotes: "Best seller item for impulse buying on mobile ads.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Portable Smart Digital Tire Inflator & 6000mAh Power Bank",
    slug: "portable-smart-digital-tire-inflator",
    description: "Cordless high-speed electric air pump for car, motorcycle, and bicycle tires with preset pressure automatic shutoff, digital LCD pressure readout, emergency LED torch light, and USB power bank port.",
    category: "Car Gadgets",
    sellingPriceLkr: 7950,
    costPriceLkr: 3800,
    sku: "CAR-PUMP-014",
    stock: 35,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1508974239320-0a029497e820?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Max Pressure": "150 PSI (10.3 Bar)",
      "Inflation Speed": "35L / min",
      "Battery": "6000mAh Rechargeable Lithium",
      "Display": "Digital Barometer LCD Screen",
    }),
    supplierLink: "https://supplier.com/product/smart-tire-inflator",
    supplierNotes: "High demand product during holiday road trips.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Bluetooth 5.3 FM Transmitter & 38W Dual USB Fast Charger",
    slug: "bluetooth-5-3-fm-transmitter-fast-charger",
    description: "Hands-free Bluetooth car adapter featuring QC3.0 + 20W Type-C PD dual fast charging ports, deep bass boost equalizer button, colorful ambient LED ring, and clear HD microphone.",
    category: "Car Gadgets",
    sellingPriceLkr: 2950,
    costPriceLkr: 1100,
    sku: "CAR-FM-015",
    stock: 60,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1586105251261-72a756497a11?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Charging": "20W Type-C PD + 18W USB QC3.0",
      "Bluetooth": "V5.3 High Speed Wireless",
      "Display": "Digital Car Battery Voltage LED",
    }),
    supplierLink: "https://supplier.com/product/car-fm-transmitter",
    supplierNotes: "High volume impulse buyer item.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "High-Power Cordless Handheld Car Vacuum Cleaner 12000Pa",
    slug: "high-power-cordless-car-vacuum-cleaner",
    description: "Ultra-compact 12000Pa powerful brushless motor vacuum cleaner with washable HEPA filter, crevice nozzle tool, and USB-C fast charging. Perfect for cleaning car seats, keyboard dust, and sofa crevices.",
    category: "Car Gadgets",
    sellingPriceLkr: 5450,
    costPriceLkr: 2400,
    sku: "CAR-VAC-016",
    stock: 40,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1586105251261-72a756497a11?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Suction Power": "12000Pa High-Speed Brushless Motor",
      "Battery": "4000mAh Li-ion (25 Mins Continuous)",
      "Filter": "Washable Stainless Steel + HEPA Dual Layer",
    }),
    supplierLink: "https://supplier.com/product/12000pa-car-vacuum",
    supplierNotes: "Includes blow nozzle attachment.",
    isFeatured: false,
    isBestSeller: true,
  },
  {
    title: "Solar-Powered Wireless Car Tire Pressure Monitoring System (TPMS)",
    slug: "solar-powered-wireless-car-tpms",
    description: "Solar panel powered dashboard TPMS display with 4 external waterproof sensor caps. Provides real-time tire pressure and temperature readouts with high/low pressure audio alarm notifications.",
    category: "Car Gadgets",
    sellingPriceLkr: 6800,
    costPriceLkr: 3100,
    sku: "CAR-TPMS-017",
    stock: 25,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Power Source": "Monocrystalline Solar Panel + Micro USB Backup",
      "Sensors": "4x External Theft-Proof IP67 Sensors",
      "Pressure Range": "0 - 5.0 Bar (0 - 72 PSI)",
    }),
    supplierLink: "https://supplier.com/product/solar-tpms-car",
    supplierNotes: "Great automotive safety accessory.",
    isFeatured: false,
    isBestSeller: false,
  },

  // --- COMPUTER ACCESSORIES CATEGORY ---
  {
    title: "Transparent Mechanical Keyboard RGB Gasket Mount (75%)",
    slug: "transparent-mechanical-keyboard-rgb",
    description: "Sleek 75% mechanical keyboard with crystal clear transparent PC casing, custom pre-lubed tactile switches, gasket mount structure for satisfying deep acoustic typing sound, and 19 RGB lighting modes.",
    category: "Computer Accessories",
    sellingPriceLkr: 16500,
    costPriceLkr: 8900,
    sku: "KB-TRN-018",
    stock: 12,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Keys": "82 Keys (75% Compact Layout)",
      "Switches": "Hot-swappable Custom Crystal Linear",
      "Connectivity": "Tri-Mode (Bluetooth 5.0 / 2.4Ghz / Type-C)",
      "Battery": "4000mAh Lithium Rechargeable",
    }),
    supplierLink: "https://supplier.com/item/transparent-gasket-kb",
    supplierNotes: "Includes keycap puller, extra switches, and braided cyan cable.",
    isFeatured: false,
    isBestSeller: true,
  },
  {
    title: "10-in-1 Aluminum USB-C Hub Docking Station 4K 60Hz",
    slug: "10-in-1-usb-c-docking-station",
    description: "Premium anodized space gray aluminum USB-C hub with HDMI 4K@60Hz, 100W Power Delivery charging port, Gigabit Ethernet RJ45, SD/TF dual card readers, and 3x USB 3.0 5Gbps ports.",
    category: "Computer Accessories",
    sellingPriceLkr: 9800,
    costPriceLkr: 4600,
    sku: "ACC-DOCK-019",
    stock: 30,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1544652478-6653e09f18a2?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Ports": "HDMI 4K, 100W PD, Gigabit LAN, SD, MicroSD, 3x USB 3.0, 3.5mm Audio",
      "Material": "Heat-Dissipating Aluminum Alloy",
      "Cable Length": "15cm Reinforced Braided Cable",
    }),
    supplierLink: "https://supplier.com/product/10in1-usbc-dock",
    supplierNotes: "Supports MacBook M1/M2/M3, Windows laptops, and iPad Pro.",
    isFeatured: false,
    isBestSeller: false,
  },
  {
    title: "Ergonomic Vertical Rechargeable Wireless Dual-Mode Mouse",
    slug: "ergonomic-vertical-rechargeable-wireless-mouse",
    description: "Scientifically designed vertical ergonomic wireless mouse preventing wrist strain and carpal tunnel syndrome. Features silent click buttons, adjustable DPI levels (800-2400), and Bluetooth + 2.4G dual connection.",
    category: "Computer Accessories",
    sellingPriceLkr: 4250,
    costPriceLkr: 1950,
    sku: "ACC-MOU-020",
    stock: 25,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "DPI Modes": "800 / 1200 / 1600 / 2400 DPI",
      "Connection": "Bluetooth 5.0 + 2.4GHz USB Dongle",
      "Battery": "500mAh USB Rechargeable",
    }),
    supplierLink: "https://supplier.com/product/vertical-mouse",
    supplierNotes: "Great impulse buy product for office workers.",
    isFeatured: false,
    isBestSeller: false,
  },
  {
    title: "1080P Full HD Webcam with Built-in Ring Light & Dual Noise Mic",
    slug: "1080p-full-hd-webcam-ring-light",
    description: "Autofocus 1080P 60fps streaming webcam featuring a 3-level touch-adjustable LED ring fill light, physical privacy shutter lens cover, dual omnidirectional noise-reducing microphones, and 360-degree swivel tripod mount.",
    category: "Computer Accessories",
    sellingPriceLkr: 7200,
    costPriceLkr: 3400,
    sku: "ACC-CAM-021",
    stock: 20,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Resolution": "1080P Full HD @ 60 FPS Autofocus",
      "Lighting": "Touch Control 3-Level Warm/Cool White LED Ring",
      "Microphone": "Dual Noise-Canceling Mics",
    }),
    supplierLink: "https://supplier.com/product/webcam-ringlight",
    supplierNotes: "Ideal for Zoom meetings, online teaching & gaming stream.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "RGB Gaming Mouse Pad 900x400mm with 15W Qi Wireless Fast Charger",
    slug: "rgb-gaming-mouse-pad-15w-wireless-charger",
    description: "Extra large XXL desk mat (900x400x4mm) featuring micro-textured cloth speed surface, non-slip rubber base, 14 RGB lighting modes edge strip, and built-in 15W wireless phone charging pad zone.",
    category: "Computer Accessories",
    sellingPriceLkr: 6850,
    costPriceLkr: 3100,
    sku: "ACC-PAD-022",
    stock: 35,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Dimensions": "900mm x 400mm x 4mm Thick",
      "Wireless Output": "15W / 10W / 7.5W Qi Fast Charging",
      "RGB Strip": "14 Light Modes with Memory Function",
    }),
    supplierLink: "https://supplier.com/product/rgb-mousepad-charger",
    supplierNotes: "High visual impact desk setup accessory.",
    isFeatured: false,
    isBestSeller: true,
  },

  // --- SMARTPHONES & MOBILE CATEGORY ---
  {
    title: "Apex Pro Mini Pocket 4G Smartphone 3-Inch Display",
    slug: "apex-pro-mini-pocket-4g-smartphone",
    description: "Ultra-compact miniature 4G Android smartphone featuring a 3.0-inch touchscreen, dual SIM standby, quad-core processor, 5MP camera, and full Google Play Store access for WhatsApp, YouTube, and banking apps.",
    category: "Smartphones",
    sellingPriceLkr: 22500,
    costPriceLkr: 12500,
    sku: "MOB-MINI-023",
    stock: 10,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Screen": "3.0-inch IPS FWVGA Touchscreen",
      "OS": "Android 12",
      "Memory": "4GB RAM + 64GB Storage",
      "Network": "4G LTE Dual Nano SIM",
      "Battery": "2000mAh",
    }),
    supplierLink: "https://supplier.com/item/mini-smartphone-4g",
    supplierNotes: "Extremely popular gadget for tech enthusiasts.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Rugged IP68 Outdoor Smartphone 10600mAh Monster Battery",
    slug: "rugged-ip68-outdoor-smartphone-10600mAh",
    description: "Heavy-duty shockproof, dustproof, and 50m waterproof outdoor Android smartphone powered by a massive 10600mAh battery (up to 30 days standby), 48MP AI camera, and super loud 3.5W speaker.",
    category: "Smartphones",
    sellingPriceLkr: 34500,
    costPriceLkr: 19500,
    sku: "MOB-RUG-024",
    stock: 8,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Battery": "10600mAh with 33W Fast Charging",
      "Durability": "IP68 / IP69K / MIL-STD-810H Certified",
      "Memory": "8GB RAM + 256GB Storage",
    }),
    supplierLink: "https://supplier.com/product/rugged-outdoor-phone",
    supplierNotes: "High ticket item with LKR 15,000 profit margin.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "MagSafe Magnetic Power Bank 10000mAh with Foldable Metal Stand",
    slug: "magsafe-magnetic-power-bank-10000mAh",
    description: "Ultra-slim 22.5W fast charging magnetic wireless power bank with 10000mAh battery capacity, LED digital battery percentage readout, foldable zinc alloy phone kickstand, and Type-C 20W PD input/output.",
    category: "Smartphones",
    sellingPriceLkr: 7850,
    costPriceLkr: 3600,
    sku: "MOB-PW-025",
    stock: 50,
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1616440342232-1594ad5ec62e?q=80&w=800&auto=format&fit=crop",
    ]),
    specs: JSON.stringify({
      "Capacity": "10000mAh (3.7V / 37Wh)",
      "Wireless Power": "15W MagSafe Fast Charge",
      "Wired Output": "22.5W Super Charge USB + 20W PD Type-C",
      "Stand": "Built-in Metal Foldable Ring Stand",
    }),
    supplierLink: "https://supplier.com/product/10000mah-magsafe-powerbank",
    supplierNotes: "Compatible with iPhone 12/13/14/15/16 and Qi devices.",
    isFeatured: true,
    isBestSeller: true,
  },
];

async function main() {
  console.log("Seeding Gizmo.lk database with expanded mock tech catalog...");

  await prisma.orderItem.deleteMany({});
  await prisma.order.deleteMany({});
  await prisma.product.deleteMany({});

  for (const item of mockProducts) {
    await prisma.product.create({
      data: item,
    });
  }

  const cyberbassProduct = await prisma.product.findFirst({ where: { sku: "AUD-CYB-001" } });

  await prisma.order.create({
    data: {
      orderNumber: "GZ-88219",
      customerName: "Kusal Perera",
      customerPhone: "+94 77 123 4567",
      customerEmail: "kusal.p@example.lk",
      address: "No. 45, Galle Road",
      district: "Colombo",
      city: "Colombo 03",
      paymentMethod: "BANK_TRANSFER",
      paymentStatus: "VERIFIED",
      orderStatus: "PROCESSING",
      bankSlipUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=600&auto=format&fit=crop",
      subtotalLkr: 8950,
      shippingFeeLkr: 350,
      totalLkr: 9300,
      notes: "Please call before dispatching.",
      items: {
        create: [
          {
            productId: cyberbassProduct.id,
            quantity: 1,
            unitPrice: 8950,
          },
        ],
      },
    },
  });

  console.log(`Database seeded successfully with ${mockProducts.length} tech products and 1 sample order!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
