import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * GIZMOTEK REAL PRODUCTS CATALOG
 * Verified 100% real dropshipping products.
 */
export const realProducts = [
  {
    title: "Power bank adapter for Fibre, 4G Router, Alarm & CCTV Security",
    slug: "power-bank-adapter-fiber-4g-router-cctv",
    description: "Reliable power bank backup solution for SLT Fibre routers, Dialog/Mobitel 4G LTE routers, ADSL modems, CCTV cameras, and security alarm systems. Features 4–6 hours uninterrupted running time during power cuts, high-quality self-replaceable battery, plug-and-play installation, and 1 Year Limited Warranty.",
    category: "Computer Accessories",
    sellingPriceLkr: 4000,
    costPriceLkr: 3240,
    sku: "26-POWER-BANK-ADAPTER-FIBER-4G-ROUTER-AL",
    stock: 299,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/b866cc2e5f4dd705beb2c5706888b082.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/ae327adea6251c7e42b1f42e309bafec.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/c298be00d9ac02348fc78e95a5c4f78c.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/a40199e65706886dec5b7e5853ec7307.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Power last",
      "Warranty": "1 Year Limited Warranty",
      "Compatible Devices": "Fibre Router, 4G/LTE Router, ADSL Modem, CCTV & Alarm Systems",
      "Backup Runtime": "Fibre (4-6 Hrs), 4G Router (5-6 Hrs), ADSL (5-6 Hrs)",
      "Battery Type": "High-Quality Self-Replaceable Battery",
      "Dimensions": "10 cm (L) x 6 cm (W) x 4 cm (H)",
      "Weight": "250 g",
      "Voltage": "100V",
      "Features": "Plug and Play, Auto-Switching Surge Protection",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/26-POWER-BANK-ADAPTER-FIBER-4G-ROUTER-AL?batchId=B-260219GWZK",
    supplierNotes: "Supplier: Scandy online market shop (Rating: 4.3). Fochant Dropshipping Price: Rs. 3,240. Margin: Rs. 760.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Brand New Fast Charging Type-C USB Data Cable",
    slug: "fast-charging-type-c-data-cable-ivon",
    description: "Premium Ivon 3.4A high-speed fast charging and data sync Type-C cable with smart LED indicator. Features reversible plug design, reinforced anti-bending joints, rapid power delivery, and universal compatibility with Android smartphones, iPhones (15/16 series), tablets, and accessories.",
    category: "Chargers & Cables",
    sellingPriceLkr: 2550,
    costPriceLkr: 2340,
    sku: "16-BRAND-NEW-FAST-CHARGING-TYPE-C-DATA-C",
    stock: 240,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/8feb2b536a6d4b2d8fb783b6bf6f8559.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Ivon",
      "Model": "IV-CA16 LED Cable",
      "Connector Type": "USB-A to Type-C Reversible",
      "Current Output": "3.4A Fast Charging",
      "Warranty": "3 Months Limited Warranty",
      "Indicator": "Built-in Smart LED Light",
      "Data Transfer": "High-Speed Data Sync",
      "Dimensions": "7 cm (L) x 4 cm (W) x 7 cm (H)",
      "Weight": "4 g",
      "Compatibility": "Samsung, Xiaomi, Apple iPhone 15/16, Huawei, Vivo, Oppo, Power Banks",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/16-BRAND-NEW-FAST-CHARGING-TYPE-C-DATA-C?batchId=B-2602095FN9",
    supplierNotes: "Supplier: Raymarts (Rating: 4.9). Fochant Dropshipping Price: Rs. 2,340. Margin: Rs. 210.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Brand New 32GB Kingston DataTraveler 50 USB 3.0 Pen Drive",
    slug: "kingston-datatraveler-50-32gb-usb-3-pen-drive",
    description: "Compact and durable Kingston DataTraveler 50 (DT50) 32GB high-speed USB 3.1 Gen 1 / USB 3.0 flash drive. Delivers fast transfer speeds up to 110MB/s read and 15MB/s write with a premium capless metal casing and red accent. Compatible with PC, Mac, laptops, TVs, and car audio systems.",
    category: "Storage & Pen Drives",
    sellingPriceLkr: 2850,
    costPriceLkr: 2580,
    sku: "16-BRAND-NEW-32GB-KINGSTON-PEN-DRIVE-HIG",
    stock: 160,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/9177066b269552b6cbb8d238a191aa63.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/82cab2cd4324dbf9ac702a5eebfc8a3b.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Kingston",
      "Model": "DataTraveler 50 (DT50)",
      "Storage Capacity": "32GB",
      "Interface": "USB 3.1 Gen 1 (USB 3.0) / Backward compatible with USB 2.0",
      "Read Speed": "Up to 110 MB/s",
      "Write Speed": "Up to 15 MB/s",
      "Design": "Capless Metal Casing with Key Ring Loop",
      "Warranty": "Checking Warranty",
      "Dimensions": "4 cm (L) x 2 cm (W) x 4 cm (H)",
      "Weight": "20 g",
      "Compatibility": "Windows 11/10/8, macOS, Linux, Chrome OS, Smart TVs",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/16-BRAND-NEW-32GB-KINGSTON-PEN-DRIVE-HIG?batchId=B-260316FCHP",
    supplierNotes: "Supplier: Raymarts (Rating: 4.3). Fochant Dropshipping Price: Rs. 2,580. Margin: Rs. 270.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Brand New 2-Meter 3.5mm Premium AUX Audio Cable",
    slug: "recrsi-aux-cable-3-5mm-audio-2m",
    description: "Premium Recrsi Silicone AUX-08 2-meter long auxiliary audio cable with corrosion-resistant 24K gold-plated 3.5mm connectors. Engineered for crystal-clear, lossless audio transmission when connecting smartphones, tablets, or laptops to car stereo systems, portable speakers, and home audio consoles.",
    category: "Audio",
    sellingPriceLkr: 1950,
    costPriceLkr: 1560,
    sku: "16-BRAND-NEW-AUX-CABLE-3-5MM-JACK-FOR-SP",
    stock: 160,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/4ba24a72b2c4f278a49ea115c9f20e41.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/8ed1773254ee5e505df83d182206c7aa.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Recrsi",
      "Model": "Silicone AUX-08",
      "Cable Length": "2 Meters (2000 mm)",
      "Connector Type": "Dual 3.5mm Male Stereo Gold-Plated Plugs",
      "Material": "Tangle-Free Flexible Silicone Jacket",
      "Warranty": "Checking Warranty",
      "Dimensions": "200 cm (Length) x 3.55 cm (W) x 4 cm (H)",
      "Weight": "280 g",
      "Compatibility": "Car Stereo Consoles, Bluetooth Speakers, Soundbars, Laptops, Smartphones, Headphones",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/16-BRAND-NEW-AUX-CABLE-3-5MM-JACK-FOR-SP?batchId=B-260316G9S3",
    supplierNotes: "Supplier: Raymarts (Rating: 4.2). Fochant Dropshipping Price: Rs. 1,560. Margin: Rs. 390.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Brand New High Speed 16GB Kingston DataTraveler 50 USB 3.0 Pen Drive",
    slug: "kingston-datatraveler-50-16gb-usb-3-pen-drive",
    description: "Compact, durable Kingston DataTraveler 50 (DT50) 16GB high-speed USB 3.1 Gen 1 / USB 3.0 flash drive. Built with a capless brushed metal casing and blue accent loop for fast, reliable on-the-go data transfer and file backup across PCs, laptops, and smart media devices.",
    category: "Storage & Pen Drives",
    sellingPriceLkr: 2150,
    costPriceLkr: 1620,
    sku: "16-BRAND-NEW-HIGH-SPEED-16GB-KINGSTON-PE",
    stock: 160,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/d480ccb72255f132cffbbf7299702c88.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/5d546ed68ed205cb104332c927642fb6.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Kingston",
      "Model": "DataTraveler 50 (DT50)",
      "Storage Capacity": "16GB",
      "Interface": "USB 3.1 Gen 1 (USB 3.0) / Backward compatible with USB 2.0",
      "Design": "Capless Metal Casing with Blue Keyring Accent",
      "Warranty": "Checking Warranty",
      "Dimensions": "4 cm (L) x 4 cm (W) x 4 cm (H)",
      "Weight": "10 g",
      "Compatibility": "Windows 11/10/8, macOS, Linux, Chrome OS, Smart TVs, Audio Systems",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/16-BRAND-NEW-HIGH-SPEED-16GB-KINGSTON-PE?batchId=B-260316CLNK",
    supplierNotes: "Supplier: Raymarts (Rating: 4.6). Fochant Dropshipping Price: Rs. 1,620. Margin: Rs. 530.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Brand New 20W Power Delivery (PD) to Type-C Fast Charging Cable",
    slug: "recrsi-pd-to-type-c-fast-charging-cable-20w",
    description: "High-performance Recrsi 20W Power Delivery (PD) Type-C to Type-C fast charging and data syncing cable (1 Meter). Features durable anti-bending reinforcement, rapid 20W power delivery, and seamless compatibility with modern Type-C smartphones (Apple iPhone 15/16 series, Samsung Galaxy, Xiaomi, Pixel), tablets, and power banks.",
    category: "Chargers & Cables",
    sellingPriceLkr: 2100,
    costPriceLkr: 1980,
    sku: "16-BRAND-NEW-TYPE-C-DATA-CABLE-FOR-MOBIL",
    stock: 160,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/81986618d9a294b49afebadab8afa44f.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/6437f252a8735b3034dd9706b78beeb4.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Recrsi",
      "Model": "PD 20W Fast Charging Cable",
      "Cable Length": "1 Meter (100 cm)",
      "Connector Type": "Type-C to Type-C",
      "Power Output": "20W Power Delivery (PD) Fast Charge",
      "Warranty": "Checking Warranty",
      "Dimensions": "100 cm (L) x 2 cm (W) x 5 cm (H)",
      "Weight": "200 g",
      "Compatibility": "iPhone 15/16, Samsung Galaxy S series, Xiaomi, iPad, Laptops, PD Power Banks",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/16-BRAND-NEW-TYPE-C-DATA-CABLE-FOR-MOBIL?batchId=B-260316ZZ9G",
    supplierNotes: "Supplier: Raymarts (Rating: 4.2). Fochant Dropshipping Price: Rs. 1,980. Margin: Rs. 120.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Remai BX-061 USB to Lightning Fast Charging iPhone Cable (1M)",
    slug: "remai-bx061-fast-charging-lightning-cable-1m",
    description: "High-speed Remai BX061 USB-A to Lightning fast charging and data sync cable (1 Meter). Built for daily durability, rapid power delivery, and simultaneous file syncing across all Lightning Apple devices including iPhone 14, 13, 12, 11, X, 8, SE, iPad, and AirPods.",
    category: "Chargers & Cables",
    sellingPriceLkr: 850,
    costPriceLkr: 540,
    sku: "7-REMAI-BX-061-FAST-CHARGING-IPHONE-CABL",
    stock: 150,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/b56aa72a7691fa20d7236858b7533ab6.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Remai",
      "Model": "BX-061 USB to Lightning",
      "Cable Length": "1 Meter (1000 mm)",
      "Connector Type": "USB-A to 8-Pin Lightning",
      "Features": "Fast Charging & Simultaneous Data Sync",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "100 cm (Length) x 10 cm (W) x 10 cm (H)",
      "Weight": "50 g",
      "Compatibility": "iPhone 14/13/12/11/X/8/7/6/SE, iPad Mini/Air, AirPods",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/7-REMAI-BX-061-FAST-CHARGING-IPHONE-CABL?batchId=B-260702P03H",
    supplierNotes: "Supplier: Ms fashion (Rating: 4.1). Fochant Dropshipping Price: Rs. 540. Margin: Rs. 310.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "3D HD Mobile Phone Screen Magnifier Amplifier (Magic Box F2)",
    slug: "3d-enlarged-screen-magic-box-phone-magnifier",
    description: "Portable 3D optical screen amplifier designed to magnify your smartphone display up to 3x–4x for an immersive mini-cinema experience. Features a foldable stand, lightweight travel-friendly design, and crystal-clear Fresnel lens that reduces eye strain when watching movies, videos, and tutorials on any iPhone or Android phone.",
    category: "Smartphones",
    sellingPriceLkr: 990,
    costPriceLkr: 450,
    sku: "3-3D-ENLARGED-SCREEN-MAGIC-BOX",
    stock: 147,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/ae9fbb8d013e5339cedae1199e9f6144.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/6820cf506296491034d232613faf2c39.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/7fb34e746fc52c5a468aa8703f776437.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/e670e5637166414ebfd0e39bf85c11aa.webp",
    ]),
    specs: JSON.stringify({
      "Model": "F2 3D Enlarged Screen Magic Box",
      "Magnification": "3x - 4x Optical Zoom",
      "Lens Type": "HD Fresnel Acrylic Optical Lens",
      "Power Source": "Zero Power / No Battery Required",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "10 cm (L) x 12 cm (W) x 12 cm (H)",
      "Weight": "200 g",
      "Features": "Foldable, Anti-Radiation, Eye-Protection, Portable",
      "Compatibility": "Universal (All iPhone & Android Smartphones)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-3D-ENLARGED-SCREEN-MAGIC-BOX?batchId=B-260728YZX0%2C%20B-2608173UOV",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 5.0). Fochant Dropshipping Price: Rs. 450. Margin: Rs. 540.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Plokama BT-10 Wireless Bluetooth Camera Shutter Remote & Self-Timer",
    slug: "plokama-bt10-wireless-bluetooth-camera-remote",
    description: "Ultra-compact Plokama BT-10 Bluetooth wireless camera shutter remote with 10-meter operating range. Features true plug-and-play pairing without needing external apps, zero shutter lag, and up to 20,000 photo/video clicks on a single CR2032 battery for group photos, vlogging, and stable tripod shots.",
    category: "Smartphones",
    sellingPriceLkr: 679,
    costPriceLkr: 485,
    sku: "3-PLOKAMA-BT10-WIRELESS-SELFTIMER",
    stock: 134,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/b8f0a5510da80aa3d5212a37602de1c5.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/4562808a647b92b783b9bd5ee98adb1b.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/dcbbbdb3f534e4ea988ab6d3dc7ffcde.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/c48ab5179d687f3bc7932b02e67799d6.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Plokama",
      "Model": "BT-10 Wireless Self-Timer",
      "Wireless Range": "Up to 10 Meters (33 Feet)",
      "Battery Type": "Pre-installed CR2032 Coin Cell (Up to 20,000 clicks)",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "4.8 cm (L) x 3.0 cm (W) x 1.0 cm (H)",
      "Weight": "30 g",
      "Features": "Plug & Play, Zero Shutter Lag, Keyring Lanyard Loop",
      "Compatibility": "iOS 6.0+ (iPhone) & Android 4.2.2+ (Samsung, Xiaomi, Vivo, Oppo, Pixel)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-PLOKAMA-BT10-WIRELESS-SELFTIMER?batchId=B-260811TYSS",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.1). Fochant Dropshipping Price: Rs. 484.80. Margin: Rs. 194.20.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Starnew X 10\"-32\" Full Motion Articulating TV & Monitor Wall Mount Bracket",
    slug: "starnew-x-full-motion-tv-monitor-wall-mount-10-32",
    description: "Heavy-duty Starnew X articulating full-motion wall mount bracket engineered for 10-inch to 32-inch LED, LCD, and computer monitor displays. Built from cold-rolled solid steel supporting up to 10 kg (22 lbs), featuring 180-degree smooth horizontal swivel, vertical tilt adjustment, universal VESA 75x75mm / 100x100mm compatibility, and built-in spirit level for effortless installation.",
    category: "Computer Accessories",
    sellingPriceLkr: 1950,
    costPriceLkr: 1391,
    sku: "3-10-32-SCREEN-FULL-MOTION-WALL-MOUNT",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/44deb05b37e6c994dd671d0338d62885.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/4411aba3f6cce69328e67afe5f877175.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/9c4e9915058c1e4b5c01fcdcd849a4cc.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/aa9aa6c0780909268c20f6ee4c269aa9.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Starnew X",
      "Compatible Screen Sizes": "10\" to 32\" Inches",
      "Max Load Capacity": "10 kg (22 lbs)",
      "VESA Compliance": "75x75 mm, 100x100 mm",
      "Motion Type": "Full Motion Articulating (180° Swivel, Vertical Tilt)",
      "Material": "Heavy-Duty High Grade Solid Steel",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "24 cm (L) x 18 cm (W) x 7 cm (H)",
      "Weight": "650 g",
      "Includes": "Mounting Hardware Kit & Integrated Spirit Level",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-10-32-SCREEN-FULL-MOTION-WALL-MOUNT",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.3). Fochant Dropshipping Price: Rs. 1,390.80. Margin: Rs. 559.20.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "2-in-1 SuperSpeed USB 3.0 OTG Adapter Cable (Type-C & Micro-USB to USB-A)",
    slug: "2-in-1-usb-3-otg-cable-type-c-micro-usb",
    description: "Versatile 2-in-1 USB On-The-Go (OTG) adapter cable featuring both Type-C and Micro-USB male connectors to standard USB 3.0 Type-A female socket. Delivers up to 5Gbps SuperSpeed data transfer (10x faster than USB 2.0). Connect pen drives, mice, keyboards, and game controllers directly to Android phones, tablets, and laptops without drivers.",
    category: "Chargers & Cables",
    sellingPriceLkr: 650,
    costPriceLkr: 370,
    sku: "3-2-IN-1-OTG-LINE",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/4b6df99f2743a105833bfbc1c90ea99a.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/f0e6de0dc27b82ae709a6db550e5de23.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/6c57731e2d973e65955d92d23c540d6b.webp",
    ]),
    specs: JSON.stringify({
      "Model": "2-in-1 OTG Adapter Line",
      "Input Connectors": "USB Type-C Male + Micro-USB Male",
      "Output Port": "USB 3.0 Type-A Female Socket",
      "Data Transfer Rate": "Up to 5 Gbps SuperSpeed",
      "Cable Material": "Reinforced Braided Jacket & Flexible Strain Relief",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "17 cm (Length) x 3 cm (W) x 3 cm (H)",
      "Weight": "50 g",
      "Features": "Plug and Play, OTG Flash Drive & Peripheral Support",
      "Compatibility": "All Type-C and Micro-USB Smartphones, Tablets, Laptops & PCs",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-2-IN-1-OTG-LINE",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.3). Fochant Dropshipping Price: Rs. 369.60. Margin: Rs. 280.40.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Audemars Piguet x Swatch Royal Pop 'OTTO ROSSO' Modular Bioceramic Watch",
    slug: "ap-x-swatch-royal-pop-otto-rosso-watch",
    description: "Iconic Audemars Piguet x Swatch 'OTTO ROSSO' modular pocket watch and neck pendant from the high-fashion Royal Pop collection. Formed from lightweight eco-friendly Bioceramic with an octagonal 8-screw Royal Oak bezel, textured tapisserie dial, mechanical SISTEM51 open exhibition caseback with 90h power reserve, and woven lanyard strap.",
    category: "Wearables",
    sellingPriceLkr: 1850,
    costPriceLkr: 1324,
    sku: "3-AP-X-SWATCH-ROYAL-POP-WATCH",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/d665d95dc379d62ca671c97ba3650571.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/08bf64df013e8e157d5158ec4d7ca834.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/0e3b2e0683728ad734c27fc1c6fa6b3d.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/ae23046c46e1adb5eae06c14a5bf6b47.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/e8453d50153256a1a472cae0b2721dfc.webp",
    ]),
    specs: JSON.stringify({
      "Collaboration": "Audemars Piguet x Swatch",
      "Model": "Royal Pop 'OTTO ROSSO'",
      "Style": "Modular Pocket Watch / Neck Pendant",
      "Case Material": "Eco-Conscious Bioceramic",
      "Movement": "SISTEM51 Mechanical with Exhibition Caseback",
      "Power Reserve": "Up to 90 Hours",
      "Dial Pattern": "Signature Miniature Petite Tapisserie",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "5.32 cm (L) x 4.0 cm (W) x 0.84 cm (H)",
      "Weight": "35 g (Ultra-Lightweight)",
      "Includes": "Detachable Bioceramic Carrier & Woven Neck Lanyard",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-AP-X-SWATCH-ROYAL-POP-WATCH",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.6). Fochant Dropshipping Price: Rs. 1,323.60. Margin: Rs. 526.40.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Apple iPhone USB Power Adapter with Lightning Cable Set",
    slug: "apple-iphone-power-adapter-lightning-cable-set",
    description: "Complete 2-in-1 iPhone charging bundle containing a compact 5W USB wall power adapter plug and a 1-meter high-speed USB-A to 8-Pin Lightning data sync cable. Equipped with built-in surge and overheat protection for reliable daily charging across Apple iPhone 14/13/12/11/X/8/7/SE series, iPad, and AirPods.",
    category: "Chargers & Cables",
    sellingPriceLkr: 1450,
    costPriceLkr: 989,
    sku: "3-APPLE-IPHONE-X-CHARGER",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/62eba5ff248e454e0f1ce6866dc6885f.webp",
    ]),
    specs: JSON.stringify({
      "Package Includes": "USB Power Adapter Wall Plug + 1M Lightning Cable",
      "Power Output": "5W Standard USB Power Adapter",
      "Cable Type": "USB-A to 8-Pin Lightning (1 Meter / 1000 mm)",
      "Safety Protection": "Overcharge, Overheat & Short-Circuit Protection",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "6 cm (L) x 6 cm (W) x 5 cm (H)",
      "Weight": "50 g",
      "Compatibility": "Apple iPhone 14/13/12/11/X/XR/XS/8/7/6/SE, iPad Mini, AirPods",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-APPLE-IPHONE-X-CHARGER",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 5.0). Fochant Dropshipping Price: Rs. 988.80. Margin: Rs. 461.20.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Quick-Release 360° Rotatable Bicycle & Motorcycle Phone Mount Holder",
    slug: "quick-release-bike-motorcycle-phone-mount-holder",
    description: "Rugged motorcycle and bicycle handlebar phone mount with instant one-handed quick-release locking mechanism. Features 4-corner claw clamps with thick shock-absorbing EVA rubber cushions, 360-degree ball joint for custom viewing angles, and universal grip fitting 4.7\" to 7.0\" smartphones on bikes, motorbikes, and scooters.",
    category: "Smartphones",
    sellingPriceLkr: 1490,
    costPriceLkr: 1042,
    sku: "3-BIKE-PHONE-MOUNT-STENTS",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/1d9be917f6e9c4e5b04e541ab931d1b7.webp",
    ]),
    specs: JSON.stringify({
      "Model": "Bike Stents Quick-Release Phone Holder",
      "Mounting Location": "Handlebar / Rearview Mirror Bar",
      "Rotation": "360° Swivel Ball Joint (Portrait & Landscape)",
      "Locking Mechanism": "One-Touch Fast Claw Auto-Lock",
      "Protection": "4-Corner Shock Absorption EVA Cushion Pads",
      "Compatible Phone Sizes": "4.7\" to 7.0\" Display Smartphones",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "14 cm (H) x 9.2 cm (W) x 3.2 cm (L)",
      "Weight": "130 g",
      "Compatibility": "Bicycles, Motorcycles, Mountain Bikes, Scooters, ATVs",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-BIKE-PHONE-MOUNT-STENTS",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.7). Fochant Dropshipping Price: Rs. 1,041.60. Margin: Rs. 448.40.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "C2 Heavy-Duty Aluminum Alloy Motorcycle Rearview Mirror Phone Holder",
    slug: "c2-aluminum-alloy-bike-mirror-phone-holder",
    description: "Premium all-metal aluminum alloy motorcycle and scooter phone mount designed for direct rearview mirror stem installation. Features rigid anti-vibration clamp brackets, 360° horizontal rotation with 120° vertical tilt, and non-slip rubber grip pads to keep your smartphone ultra-stable during high-speed rides and rough terrain.",
    category: "Smartphones",
    sellingPriceLkr: 990,
    costPriceLkr: 672,
    sku: "3-C2-BIKE-MIRROR-PHONE-HOLDER",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/064eba1f7a91ac6c8699b277eb89ae66.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/a2951cafff1d6273b103efa9d9f4ef7e.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/29783fa1688ea01b96213c5813c7c88f.webp",
    ]),
    specs: JSON.stringify({
      "Model": "C2 Rearview Mirror Phone Mount",
      "Mounting Position": "Motorcycle & Scooter Rearview Mirror Stem",
      "Material": "Reinforced Aluminum Alloy Metal Body",
      "Adjustability": "360° Horizontal Rotation & 120° Vertical Tilt",
      "Clamp Range": "Fits 4.0\" to 6.8\" Smartphones",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "10.5 cm (H) x 8 cm (L) x 6 cm (W)",
      "Weight": "200 g",
      "Compatibility": "Motorcycles, Scooters, E-Bikes, Mopeds",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-C2-BIKE-MIRROR-PHONE-HOLDER",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.4). Fochant Dropshipping Price: Rs. 672.00. Margin: Rs. 318.00.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Century Home 10000mAh Mini Pocket Power Bank with Digital Display & Torch",
    slug: "century-home-10000mah-mini-pocket-power-bank",
    description: "Ultra-compact square 10000mAh portable power bank charger featuring a sleek digital LED battery display, triple 2.1A output ports for simultaneous multi-device charging, integrated carry lanyard loop, and built-in bright emergency LED flashlight. High-density battery cell designed for daily commute, travels, and emergency power backup.",
    category: "Chargers & Cables",
    sellingPriceLkr: 4450,
    costPriceLkr: 3140,
    sku: "3-CENTURY-HOME-POWER-BANK",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/103af793b3534fa186aa6156d99097df.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/6102552951488abda0bc6aa51c8e60fb.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/442fe6f2c099a80b0869886f96e778bd.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Century Home",
      "Battery Capacity": "10000 mAh High-Density Cell",
      "Display": "Glossy Digital LED Battery Indicator (25%, 50%, 75%, 100%)",
      "Output Ports": "Triple USB Output (2.1A Max Output Delivery)",
      "Flashlight": "Integrated Bright Emergency LED Torch",
      "Form Factor": "Pocket-Sized Square Mini Body with Lanyard Strap",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "9.1 cm (H) x 7.8 cm (W) x 2.6 cm (L)",
      "Weight": "211 g",
      "Compatibility": "Universal (iPhone, Android, Tablets, Bluetooth Earbuds, Smartwatches)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-CENTURY-HOME-POWER-BANK",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.3). Fochant Dropshipping Price: Rs. 3,139.20. Margin: Rs. 1,310.80.",
    isFeatured: true,
    isBestSeller: true,
  },
];

async function main() {
  console.log("Cleaning all mock data and seeding GizmoTek.lk database with real products...");

  // Delete all existing items, orders, reviews, and products
  await prisma.orderItem.deleteMany({});
  await prisma.order.deleteMany({});
  try {
    await prisma.review.deleteMany({});
  } catch (err) {}
  await prisma.product.deleteMany({});

  console.log("Database cleared.");

  // Insert real products
  for (const item of realProducts) {
    await prisma.product.create({
      data: item,
    });
  }

  console.log(`Database successfully initialized with ${realProducts.length} real products!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
