import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * GIZMOTEK REAL PRODUCTS CATALOG
 * Verified 100% real dropshipping products.
 */
export const realProducts: any[] = [
  {
    title: "Power bank adapter for Fibre, 4G Router, Alarm & CCTV Security",
    slug: "power-bank-adapter-fiber-4g-router-cctv",
    description: "Reliable power bank backup solution for SLT Fibre routers, Dialog/Mobitel 4G LTE routers, ADSL modems, CCTV cameras, and security alarm systems. Features 4–6 hours uninterrupted running time during power cuts, high-quality self-replaceable battery, plug-and-play installation, and 1 Year Limited Warranty.",
    category: "Computer Accessories",
    sellingPriceLkr: 4000,
    costPriceLkr: 3240,
    sku: "26-POWER-BANK-ADAPTER-FIBER-4G-ROUTER-AL",
    stock: 299,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/b866cc2e5f4dd705beb2c5706888b082.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/ae327adea6251c7e42b1f42e309bafec.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/c298be00d9ac02348fc78e95a5c4f78c.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/a40199e65706886dec5b7e5853ec7307.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Power last",
      "Warranty": "1 Year Limited Warranty",
      "Compatible Devices": "Fibre Router, 4G/LTE Router, ADSL Modem, CCTV & Alarm Systems",
      "Backup Runtime": "Fibre (4-6 Hrs), 4G Router (5-6 Hrs), ADSL (5-6 Hrs)",
      "Battery Type": "High-Quality Self-Replaceable Battery",
      "Dimensions": "10 cm (L) x 6 cm (W) x 4 cm (H)",
      "Weight": "250 g",
      "Voltage": "100V",
      "Features": "Plug and Play, Auto-Switching Surge Protection",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/26-POWER-BANK-ADAPTER-FIBER-4G-ROUTER-AL?batchId=B-260219GWZK",
    supplierNotes: "Supplier: Scandy online market shop (Rating: 4.3). Fochant Dropshipping Price: Rs. 3,240. Margin: Rs. 760.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Brand New Fast Charging Type-C USB Data Cable",
    slug: "fast-charging-type-c-data-cable-ivon",
    description: "Premium Ivon 3.4A high-speed fast charging and data sync Type-C cable with smart LED indicator. Features reversible plug design, reinforced anti-bending joints, rapid power delivery, and universal compatibility with Android smartphones, iPhones (15/16 series), tablets, and accessories.",
    category: "Chargers & Cables",
    sellingPriceLkr: 2550,
    costPriceLkr: 2340,
    sku: "16-BRAND-NEW-FAST-CHARGING-TYPE-C-DATA-C",
    stock: 240,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/8feb2b536a6d4b2d8fb783b6bf6f8559.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Ivon",
      "Model": "IV-CA16 LED Cable",
      "Connector Type": "USB-A to Type-C Reversible",
      "Current Output": "3.4A Fast Charging",
      "Warranty": "3 Months Limited Warranty",
      "Indicator": "Built-in Smart LED Light",
      "Data Transfer": "High-Speed Data Sync",
      "Dimensions": "7 cm (L) x 4 cm (W) x 7 cm (H)",
      "Weight": "4 g",
      "Compatibility": "Samsung, Xiaomi, Apple iPhone 15/16, Huawei, Vivo, Oppo, Power Banks",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/16-BRAND-NEW-FAST-CHARGING-TYPE-C-DATA-C?batchId=B-2602095FN9",
    supplierNotes: "Supplier: Raymarts (Rating: 4.9). Fochant Dropshipping Price: Rs. 2,340. Margin: Rs. 210.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Brand New 32GB Kingston DataTraveler 50 USB 3.0 Pen Drive",
    slug: "kingston-datatraveler-50-32gb-usb-3-pen-drive",
    description: "Compact and durable Kingston DataTraveler 50 (DT50) 32GB high-speed USB 3.1 Gen 1 / USB 3.0 flash drive. Delivers fast transfer speeds up to 110MB/s read and 15MB/s write with a premium capless metal casing and red accent. Compatible with PC, Mac, laptops, TVs, and car audio systems.",
    category: "Storage & Pen Drives",
    sellingPriceLkr: 2850,
    costPriceLkr: 2580,
    sku: "16-BRAND-NEW-32GB-KINGSTON-PEN-DRIVE-HIG",
    stock: 160,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/9177066b269552b6cbb8d238a191aa63.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/82cab2cd4324dbf9ac702a5eebfc8a3b.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Kingston",
      "Model": "DataTraveler 50 (DT50)",
      "Storage Capacity": "32GB",
      "Interface": "USB 3.1 Gen 1 (USB 3.0) / Backward compatible with USB 2.0",
      "Read Speed": "Up to 110 MB/s",
      "Write Speed": "Up to 15 MB/s",
      "Design": "Capless Metal Casing with Key Ring Loop",
      "Warranty": "Checking Warranty",
      "Dimensions": "4 cm (L) x 2 cm (W) x 4 cm (H)",
      "Weight": "20 g",
      "Compatibility": "Windows 11/10/8, macOS, Linux, Chrome OS, Smart TVs",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/16-BRAND-NEW-32GB-KINGSTON-PEN-DRIVE-HIG?batchId=B-260316FCHP",
    supplierNotes: "Supplier: Raymarts (Rating: 4.3). Fochant Dropshipping Price: Rs. 2,580. Margin: Rs. 270.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Brand New 2-Meter 3.5mm Premium AUX Audio Cable",
    slug: "recrsi-aux-cable-3-5mm-audio-2m",
    description: "Premium Recrsi Silicone AUX-08 2-meter long auxiliary audio cable with corrosion-resistant 24K gold-plated 3.5mm connectors. Engineered for crystal-clear, lossless audio transmission when connecting smartphones, tablets, or laptops to car stereo systems, portable speakers, and home audio consoles.",
    category: "Audio",
    sellingPriceLkr: 1950,
    costPriceLkr: 1560,
    sku: "16-BRAND-NEW-AUX-CABLE-3-5MM-JACK-FOR-SP",
    stock: 160,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/4ba24a72b2c4f278a49ea115c9f20e41.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/8ed1773254ee5e505df83d182206c7aa.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Recrsi",
      "Model": "Silicone AUX-08",
      "Cable Length": "2 Meters (2000 mm)",
      "Connector Type": "Dual 3.5mm Male Stereo Gold-Plated Plugs",
      "Material": "Tangle-Free Flexible Silicone Jacket",
      "Warranty": "Checking Warranty",
      "Dimensions": "200 cm (Length) x 3.55 cm (W) x 4 cm (H)",
      "Weight": "280 g",
      "Compatibility": "Car Stereo Consoles, Bluetooth Speakers, Soundbars, Laptops, Smartphones, Headphones",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/16-BRAND-NEW-AUX-CABLE-3-5MM-JACK-FOR-SP?batchId=B-260316G9S3",
    supplierNotes: "Supplier: Raymarts (Rating: 4.2). Fochant Dropshipping Price: Rs. 1,560. Margin: Rs. 390.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Brand New High Speed 16GB Kingston DataTraveler 50 USB 3.0 Pen Drive",
    slug: "kingston-datatraveler-50-16gb-usb-3-pen-drive",
    description: "Compact, durable Kingston DataTraveler 50 (DT50) 16GB high-speed USB 3.1 Gen 1 / USB 3.0 flash drive. Built with a capless brushed metal casing and blue accent loop for fast, reliable on-the-go data transfer and file backup across PCs, laptops, and smart media devices.",
    category: "Storage & Pen Drives",
    sellingPriceLkr: 2150,
    costPriceLkr: 1620,
    sku: "16-BRAND-NEW-HIGH-SPEED-16GB-KINGSTON-PE",
    stock: 160,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/d480ccb72255f132cffbbf7299702c88.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/5d546ed68ed205cb104332c927642fb6.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Kingston",
      "Model": "DataTraveler 50 (DT50)",
      "Storage Capacity": "16GB",
      "Interface": "USB 3.1 Gen 1 (USB 3.0) / Backward compatible with USB 2.0",
      "Design": "Capless Metal Casing with Blue Keyring Accent",
      "Warranty": "Checking Warranty",
      "Dimensions": "4 cm (L) x 4 cm (W) x 4 cm (H)",
      "Weight": "10 g",
      "Compatibility": "Windows 11/10/8, macOS, Linux, Chrome OS, Smart TVs, Audio Systems",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/16-BRAND-NEW-HIGH-SPEED-16GB-KINGSTON-PE?batchId=B-260316CLNK",
    supplierNotes: "Supplier: Raymarts (Rating: 4.6). Fochant Dropshipping Price: Rs. 1,620. Margin: Rs. 530.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Brand New 20W Power Delivery (PD) to Type-C Fast Charging Cable",
    slug: "recrsi-pd-to-type-c-fast-charging-cable-20w",
    description: "High-performance Recrsi 20W Power Delivery (PD) Type-C to Type-C fast charging and data syncing cable (1 Meter). Features durable anti-bending reinforcement, rapid 20W power delivery, and seamless compatibility with modern Type-C smartphones (Apple iPhone 15/16 series, Samsung Galaxy, Xiaomi, Pixel), tablets, and power banks.",
    category: "Chargers & Cables",
    sellingPriceLkr: 2100,
    costPriceLkr: 1980,
    sku: "16-BRAND-NEW-TYPE-C-DATA-CABLE-FOR-MOBIL",
    stock: 160,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/81986618d9a294b49afebadab8afa44f.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/6437f252a8735b3034dd9706b78beeb4.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Recrsi",
      "Model": "PD 20W Fast Charging Cable",
      "Cable Length": "1 Meter (100 cm)",
      "Connector Type": "Type-C to Type-C",
      "Power Output": "20W Power Delivery (PD) Fast Charge",
      "Warranty": "Checking Warranty",
      "Dimensions": "100 cm (L) x 2 cm (W) x 5 cm (H)",
      "Weight": "200 g",
      "Compatibility": "iPhone 15/16, Samsung Galaxy S series, Xiaomi, iPad, Laptops, PD Power Banks",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/16-BRAND-NEW-TYPE-C-DATA-CABLE-FOR-MOBIL?batchId=B-260316ZZ9G",
    supplierNotes: "Supplier: Raymarts (Rating: 4.2). Fochant Dropshipping Price: Rs. 1,980. Margin: Rs. 120.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Remai BX-061 USB to Lightning Fast Charging iPhone Cable (1M)",
    slug: "remai-bx061-fast-charging-lightning-cable-1m",
    description: "High-speed Remai BX061 USB-A to Lightning fast charging and data sync cable (1 Meter). Built for daily durability, rapid power delivery, and simultaneous file syncing across all Lightning Apple devices including iPhone 14, 13, 12, 11, X, 8, SE, iPad, and AirPods.",
    category: "Chargers & Cables",
    sellingPriceLkr: 850,
    costPriceLkr: 540,
    sku: "7-REMAI-BX-061-FAST-CHARGING-IPHONE-CABL",
    stock: 150,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/b56aa72a7691fa20d7236858b7533ab6.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Remai",
      "Model": "BX-061 USB to Lightning",
      "Cable Length": "1 Meter (1000 mm)",
      "Connector Type": "USB-A to 8-Pin Lightning",
      "Features": "Fast Charging & Simultaneous Data Sync",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "100 cm (Length) x 10 cm (W) x 10 cm (H)",
      "Weight": "50 g",
      "Compatibility": "iPhone 14/13/12/11/X/8/7/6/SE, iPad Mini/Air, AirPods",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/7-REMAI-BX-061-FAST-CHARGING-IPHONE-CABL?batchId=B-260702P03H",
    supplierNotes: "Supplier: Ms fashion (Rating: 4.1). Fochant Dropshipping Price: Rs. 540. Margin: Rs. 310.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "3D HD Mobile Phone Screen Magnifier Amplifier (Magic Box F2)",
    slug: "3d-enlarged-screen-magic-box-phone-magnifier",
    description: "Portable 3D optical screen amplifier designed to magnify your smartphone display up to 3x–4x for an immersive mini-cinema experience. Features a foldable stand, lightweight travel-friendly design, and crystal-clear Fresnel lens that reduces eye strain when watching movies, videos, and tutorials on any iPhone or Android phone.",
    category: "Smartphones",
    sellingPriceLkr: 990,
    costPriceLkr: 450,
    sku: "3-3D-ENLARGED-SCREEN-MAGIC-BOX",
    stock: 147,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/ae9fbb8d013e5339cedae1199e9f6144.webp",
      "https://fochant-prod.s3.ap-enjoyable-1.amazonaws.com/testfolder/product_image/6820cf506296491034d232613faf2c39.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/7fb34e746fc52c5a468aa8703f776437.webp",
      "https://fochant-prod.s3.ap-enjoyable-1.amazonaws.com/testfolder/product_image/e670e5637166414ebfd0e39bf85c11aa.webp",
    ]),
    specs: JSON.stringify({
      "Model": "F2 3D Enlarged Screen Magic Box",
      "Magnification": "3x - 4x Optical Zoom",
      "Lens Type": "HD Fresnel Acrylic Optical Lens",
      "Power Source": "Zero Power / No Battery Required",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "10 cm (L) x 12 cm (W) x 12 cm (H)",
      "Weight": "200 g",
      "Features": "Foldable, Anti-Radiation, Eye-Protection, Portable",
      "Compatibility": "Universal (All iPhone & Android Smartphones)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-3D-ENLARGED-SCREEN-MAGIC-BOX?batchId=B-260728YZX0%2C%20B-2608173UOV",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 5.0). Fochant Dropshipping Price: Rs. 450. Margin: Rs. 540.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Plokama BT-10 Wireless Bluetooth Camera Shutter Remote & Self-Timer",
    slug: "plokama-bt10-wireless-bluetooth-camera-remote",
    description: "Ultra-compact Plokama BT-10 Bluetooth wireless camera shutter remote with 10-meter operating range. Features true plug-and-play pairing without needing external apps, zero shutter lag, and up to 20,000 photo/video clicks on a single CR2032 battery for group photos, vlogging, and stable tripod shots.",
    category: "Smartphones",
    sellingPriceLkr: 679,
    costPriceLkr: 485,
    sku: "3-PLOKAMA-BT10-WIRELESS-SELFTIMER",
    stock: 134,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/b8f0a5510da80aa3d5212a37602de1c5.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/4562808a647b92b783b9bd5ee98adb1b.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/dcbbbdb3f534e4ea988ab6d3dc7ffcde.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/c48ab5179d687f3bc7932b02e67799d6.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Plokama",
      "Model": "BT-10 Wireless Self-Timer",
      "Wireless Range": "Up to 10 Meters (33 Feet)",
      "Battery Type": "Pre-installed CR2032 Coin Cell (Up to 20,000 clicks)",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "4.8 cm (L) x 3.0 cm (W) x 1.0 cm (H)",
      "Weight": "30 g",
      "Features": "Plug & Play, Zero Shutter Lag, Keyring Lanyard Loop",
      "Compatibility": "iOS 6.0+ (iPhone) & Android 4.2.2+ (Samsung, Xiaomi, Vivo, Oppo, Pixel)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-PLOKAMA-BT10-WIRELESS-SELFTIMER?batchId=B-260811TYSS",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.1). Fochant Dropshipping Price: Rs. 484.80. Margin: Rs. 194.20.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Starnew X 10\"-32\" Full Motion Articulating TV & Monitor Wall Mount Bracket",
    slug: "starnew-x-full-motion-tv-monitor-wall-mount-10-32",
    description: "Heavy-duty Starnew X articulating full-motion wall mount bracket engineered for 10-inch to 32-inch LED, LCD, and computer monitor displays. Built from cold-rolled solid steel supporting up to 10 kg (22 lbs), featuring 180-degree smooth horizontal swivel, vertical tilt adjustment, universal VESA 75x75mm / 100x100mm compatibility, and built-in spirit level for effortless installation.",
    category: "Computer Accessories",
    sellingPriceLkr: 1950,
    costPriceLkr: 1391,
    sku: "3-10-32-SCREEN-FULL-MOTION-WALL-MOUNT",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/44deb05b37e6c994dd671d0338d62885.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/4411aba3f6cce69328e67afe5f877175.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/9c4e9915058c1e4b5c01fcdcd849a4cc.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/aa9aa6c0780909268c20f6ee4c269aa9.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Starnew X",
      "Compatible Screen Sizes": "10\" to 32\" Inches",
      "Max Load Capacity": "10 kg (22 lbs)",
      "VESA Compliance": "75x75 mm, 100x100 mm",
      "Motion Type": "Full Motion Articulating (180° Swivel, Vertical Tilt)",
      "Material": "Heavy-Duty High Grade Solid Steel",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "24 cm (L) x 18 cm (W) x 7 cm (H)",
      "Weight": "650 g",
      "Includes": "Mounting Hardware Kit & Integrated Spirit Level",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-10-32-SCREEN-FULL-MOTION-WALL-MOUNT",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.3). Fochant Dropshipping Price: Rs. 1,390.80. Margin: Rs. 559.20.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "2-in-1 SuperSpeed USB 3.0 OTG Adapter Cable (Type-C & Micro-USB to USB-A)",
    slug: "2-in-1-usb-3-otg-cable-type-c-micro-usb",
    description: "Versatile 2-in-1 USB On-The-Go (OTG) adapter cable featuring both Type-C and Micro-USB male connectors to standard USB 3.0 Type-A female socket. Delivers up to 5Gbps SuperSpeed data transfer (10x faster than USB 2.0). Connect pen drives, mice, keyboards, and game controllers directly to Android phones, tablets, and laptops without drivers.",
    category: "Chargers & Cables",
    sellingPriceLkr: 650,
    costPriceLkr: 370,
    sku: "3-2-IN-1-OTG-LINE",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/4b6df99f2743a105833bfbc1c90ea99a.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/f0e6de0dc27b82ae709a6db550e5de23.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/6c57731e2d973e65955d92d23c540d6b.webp",
    ]),
    specs: JSON.stringify({
      "Model": "2-in-1 OTG Adapter Line",
      "Input Connectors": "USB Type-C Male + Micro-USB Male",
      "Output Port": "USB 3.0 Type-A Female Socket",
      "Data Transfer Rate": "Up to 5 Gbps SuperSpeed",
      "Cable Material": "Reinforced Braided Jacket & Flexible Strain Relief",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "17 cm (Length) x 3 cm (W) x 3 cm (H)",
      "Weight": "50 g",
      "Features": "Plug and Play, OTG Flash Drive & Peripheral Support",
      "Compatibility": "All Type-C and Micro-USB Smartphones, Tablets, Laptops & PCs",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-2-IN-1-OTG-LINE",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.3). Fochant Dropshipping Price: Rs. 369.60. Margin: Rs. 280.40.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Audemars Piguet x Swatch Royal Pop 'OTTO ROSSO' Modular Bioceramic Watch",
    slug: "ap-x-swatch-royal-pop-otto-rosso-watch",
    description: "Iconic Audemars Piguet x Swatch 'OTTO ROSSO' modular pocket watch and neck pendant from the high-fashion Royal Pop collection. Formed from lightweight eco-friendly Bioceramic with an octagonal 8-screw Royal Oak bezel, textured tapisserie dial, mechanical SISTEM51 open exhibition caseback with 90h power reserve, and woven lanyard strap.",
    category: "Wearables",
    sellingPriceLkr: 1850,
    costPriceLkr: 1324,
    sku: "3-AP-X-SWATCH-ROYAL-POP-WATCH",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/d665d95dc379d62ca671c97ba3650571.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/08bf64df013e8e157d5158ec4d7ca834.webp",
      "https://fochant-prod.s3.ap-enjoyable-1.amazonaws.com/testfolder/product_image/0e3b2e0683728ad734c27fc1c6fa6b3d.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/ae23046c46e1adb5eae06c14a5bf6b47.webp",
      "https://fochant-prod.s3.ap-enjoyable-1.amazonaws.com/testfolder/product_image/e8453d50153256a1a472cae0b2721dfc.webp",
    ]),
    specs: JSON.stringify({
      "Collaboration": "Audemars Piguet x Swatch",
      "Model": "Royal Pop 'OTTO ROSSO'",
      "Style": "Modular Pocket Watch / Neck Pendant",
      "Case Material": "Eco-Conscious Bioceramic",
      "Movement": "SISTEM51 Mechanical with Exhibition Caseback",
      "Power Reserve": "Up to 90 Hours",
      "Dial Pattern": "Signature Miniature Petite Tapisserie",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "5.32 cm (L) x 4.0 cm (W) x 0.84 cm (H)",
      "Weight": "35 g (Ultra-Lightweight)",
      "Includes": "Detachable Bioceramic Carrier & Woven Neck Lanyard",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-AP-X-SWATCH-ROYAL-POP-WATCH",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.6). Fochant Dropshipping Price: Rs. 1,323.60. Margin: Rs. 526.40.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Apple iPhone USB Power Adapter with Lightning Cable Set",
    slug: "apple-iphone-power-adapter-lightning-cable-set",
    description: "Complete 2-in-1 iPhone charging bundle containing a compact 5W USB wall power adapter plug and a 1-meter high-speed USB-A to 8-Pin Lightning data sync cable. Equipped with built-in surge and overheat protection for reliable daily charging across Apple iPhone 14/13/12/11/X/8/7/SE series, iPad, and AirPods.",
    category: "Chargers & Cables",
    sellingPriceLkr: 1450,
    costPriceLkr: 989,
    sku: "3-APPLE-IPHONE-X-CHARGER",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/62eba5ff248e454e0f1ce6866dc6885f.webp",
    ]),
    specs: JSON.stringify({
      "Package Includes": "USB Power Adapter Wall Plug + 1M Lightning Cable",
      "Power Output": "5W Standard USB Power Adapter",
      "Cable Type": "USB-A to 8-Pin Lightning (1 Meter / 1000 mm)",
      "Safety Protection": "Overcharge, Overheat & Short-Circuit Protection",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "6 cm (L) x 6 cm (W) x 5 cm (H)",
      "Weight": "50 g",
      "Compatibility": "Apple iPhone 14/13/12/11/X/XR/XS/8/7/6/SE, iPad Mini, AirPods",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-APPLE-IPHONE-X-CHARGER",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 5.0). Fochant Dropshipping Price: Rs. 988.80. Margin: Rs. 461.20.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Quick-Release 360° Rotatable Bicycle & Motorcycle Phone Mount Holder",
    slug: "quick-release-bike-motorcycle-phone-mount-holder",
    description: "Rugged motorcycle and bicycle handlebar phone mount with instant one-handed quick-release locking mechanism. Features 4-corner claw clamps with thick shock-absorbing EVA rubber cushions, 360-degree ball joint for custom viewing angles, and universal grip fitting 4.7\" to 7.0\" smartphones on bikes, motorbikes, and scooters.",
    category: "Smartphones",
    sellingPriceLkr: 1490,
    costPriceLkr: 1042,
    sku: "3-BIKE-PHONE-MOUNT-STENTS",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/1d9be917f6e9c4e5b04e541ab931d1b7.webp",
    ]),
    specs: JSON.stringify({
      "Model": "Bike Stents Quick-Release Phone Holder",
      "Mounting Location": "Handlebar / Rearview Mirror Bar",
      "Rotation": "360° Swivel Ball Joint (Portrait & Landscape)",
      "Locking Mechanism": "One-Touch Fast Claw Auto-Lock",
      "Protection": "4-Corner Shock Absorption EVA Cushion Pads",
      "Compatible Phone Sizes": "4.7\" to 7.0\" Display Smartphones",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "14 cm (H) x 9.2 cm (W) x 3.2 cm (L)",
      "Weight": "130 g",
      "Compatibility": "Bicycles, Motorcycles, Mountain Bikes, Scooters, ATVs",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-BIKE-PHONE-MOUNT-STENTS",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.7). Fochant Dropshipping Price: Rs. 1,041.60. Margin: Rs. 448.40.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "C2 Heavy-Duty Aluminum Alloy Motorcycle Rearview Mirror Phone Holder",
    slug: "c2-aluminum-alloy-bike-mirror-phone-holder",
    description: "Premium all-metal aluminum alloy motorcycle and scooter phone mount designed for direct rearview mirror stem installation. Features rigid anti-vibration clamp brackets, 360° horizontal rotation with 120° vertical tilt, and non-slip rubber grip pads to keep your smartphone ultra-stable during high-speed rides and rough terrain.",
    category: "Smartphones",
    sellingPriceLkr: 990,
    costPriceLkr: 672,
    sku: "3-C2-BIKE-MIRROR-PHONE-HOLDER",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-enjoyable-1.amazonaws.com/testfolder/product_image/064eba1f7a91ac6c8699b277eb89ae66.webp",
      "https://fochant-prod.s3.ap-enjoyable-1.amazonaws.com/testfolder/product_image/a2951cafff1d6273b103efa9d9f4ef7e.webp",
      "https://fochant-prod.s3.ap-enjoyable-1.amazonaws.com/testfolder/product_image/29783fa1688ea01b96213c5813c7c88f.webp",
    ]),
    specs: JSON.stringify({
      "Model": "C2 Rearview Mirror Phone Mount",
      "Mounting Position": "Motorcycle & Scooter Rearview Mirror Stem",
      "Material": "Reinforced Aluminum Alloy Metal Body",
      "Adjustability": "360° Horizontal Rotation & 120° Vertical Tilt",
      "Clamp Range": "Fits 4.0\" to 6.8\" Smartphones",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "10.5 cm (H) x 8 cm (L) x 6 cm (W)",
      "Weight": "200 g",
      "Compatibility": "Motorcycles, Scooters, E-Bikes, Mopeds",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-C2-BIKE-MIRROR-PHONE-HOLDER",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.4). Fochant Dropshipping Price: Rs. 672.00. Margin: Rs. 318.00.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Century Home 10000mAh Mini Pocket Power Bank with Digital Display & Torch",
    slug: "century-home-10000mah-mini-pocket-power-bank",
    description: "Ultra-compact square 10000mAh portable power bank charger featuring a sleek digital LED battery display, triple 2.1A output ports for simultaneous multi-device charging, integrated carry lanyard loop, and built-in bright emergency LED flashlight. High-density battery cell designed for daily commute, travels, and emergency power backup.",
    category: "Chargers & Cables",
    sellingPriceLkr: 4450,
    costPriceLkr: 3140,
    sku: "3-CENTURY-HOME-POWER-BANK",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/103af793b3534fa186aa6156d99097df.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/6102552951488abda0bc6aa51c8e60fb.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/442fe6f2c099a80b0869886f96e778bd.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Century Home",
      "Battery Capacity": "10000 mAh High-Density Cell",
      "Display": "Glossy Digital LED Battery Indicator (25%, 50%, 75%, 100%)",
      "Output Ports": "Triple USB Output (2.1A Max Output Delivery)",
      "Flashlight": "Integrated Bright Emergency LED Torch",
      "Form Factor": "Pocket-Sized Square Mini Body with Lanyard Strap",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "9.1 cm (H) x 7.8 cm (W) x 2.6 cm (L)",
      "Weight": "211 g",
      "Compatibility": "Universal (iPhone, Android, Tablets, Bluetooth Earbuds, Smartwatches)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-CENTURY-HOME-POWER-BANK",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.3). Fochant Dropshipping Price: Rs. 3,139.20. Margin: Rs. 1,310.80.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Crystal Clear MagSafe Magnetic Shockproof Protective Phone Case",
    slug: "clear-magsafe-protective-phone-case",
    description: "Premium crystal-clear slim protective case engineered with an integrated high-grade magnetic array for fast, seamless MagSafe wireless charging and magnetic car mount attachment. Features anti-yellowing optical polycarbonate, shock-absorbing flexible TPU bumpers, raised camera bezels, and responsive tactile buttons.",
    category: "Smartphones",
    sellingPriceLkr: 1150,
    costPriceLkr: 719,
    sku: "3-CLEAR-MAGSAFE-PROTECTIVE-PHONE-CASE",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/0ba67893974d6dd49737f2ff4d134ea6.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/df73aea6b581115d50c6bb7eb9bdbc38.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/2a4538ea676df880abcc040c4dd3301e.webp",
    ]),
    specs: JSON.stringify({
      "Model": "Crystal Clear MagSafe Protective Series",
      "Material": "Anti-Yellowing Polycarbonate + Flexible TPU Frame",
      "Magnetic Ring": "Integrated Precision MagSafe Magnetic Array",
      "Protection": "Shock-Absorbing Air-Cushioned Corners & Raised Camera Lip",
      "Wireless Charging": "100% Compatible with MagSafe & Qi Wireless Chargers",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "15.2 cm (H) x 7.6 cm (W) x 1.0 cm (Thickness)",
      "Weight": "30 g (Ultra-Lightweight)",
      "Compatibility": "Apple iPhone & Samsung Galaxy Ultra Flagship Series",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-CLEAR-MAGSAFE-PROTECTIVE-PHONE-CASE",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.6). Fochant Dropshipping Price: Rs. 718.80. Margin: Rs. 431.20.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Universal Multi-Angle Foldable Pocket Desk Phone & Tablet Stand",
    slug: "compact-foldable-desk-phone-stand",
    description: "Ultra-portable multi-angle foldable desktop phone and mini-tablet stand. Engineered with a multi-groove incline track for instant ergonomic angle adjustments, anti-slip soft silicone front lip padding, and a collapse-flat design (under 1 cm thickness) that easily slips into your pocket or laptop bag for travel, work, and video calls.",
    category: "Smartphones",
    sellingPriceLkr: 550,
    costPriceLkr: 316,
    sku: "3-COMPACT-FOLDABLE-DESK-PHONE-STAND",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/e30a62ddd4a3e93bb18d7810a00e1957.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/a5a5eca6b2e77a4855422334c87ee69d.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/1108cb3c54227ff102d54c03e4a5cd90.webp",
    ]),
    specs: JSON.stringify({
      "Model": "Compact Folding Desktop Stand",
      "Adjustability": "Multi-Slot Grooved Track Angle Adjustment",
      "Orientation": "Dual Support (Portrait & Landscape)",
      "Protection": "Anti-Scratch Non-Slip Silicone Cushion Lip",
      "Folded Profile": "Ultra-Slim Flat Fold (Under 1 cm)",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "8.2 cm (L) x 7.1 cm (W) x 1.0 cm (H)",
      "Weight": "20 g (Pocket-Friendly)",
      "Compatibility": "Universal (All iPhone, Android Phones, E-Readers & Mini-Tablets)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-COMPACT-FOLDABLE-DESK-PHONE-STAND",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.3). Fochant Dropshipping Price: Rs. 315.60. Margin: Rs. 234.40.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "DELL 2.4GHz Ergonomic Optical Wireless Mouse with Nano USB Receiver",
    slug: "dell-wireless-mouse-2-4ghz",
    description: "Reliable Dell 2.4 GHz wireless optical mouse engineered for clutter-free desktop productivity and laptop computing. Features plug-and-play convenience via compact nano USB receiver, responsive 1000 DPI optical tracking sensor, ergonomic contoured grip for all-day hand comfort, and long-lasting battery life with smart sleep mode.",
    category: "Computer Accessories",
    sellingPriceLkr: 1850,
    costPriceLkr: 1256,
    sku: "3-DELL-WIRELESS-MOUSE-2-4-GHZ",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/2d29f1e9bd6d92b9bb77c4398e774024.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/26da7db952ffdf6bebe0010ba43fbb12.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/d7e029f358293fa4ebe0d62e0eb71397.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Dell",
      "Connectivity": "2.4 GHz RF Wireless (Nano USB Receiver Included)",
      "Sensor Technology": "High-Precision 1000 DPI Optical Tracking",
      "Buttons": "3 Buttons (Left Click, Right Click, Clickable Scroll Wheel)",
      "Design": "Comfortable Ambidextrous Contoured Grip",
      "Power Management": "Smart Auto-Sleep Battery Saving Mode",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "10 cm (L) x 6.5 cm (W) x 4 cm (H)",
      "Weight": "110 g",
      "Compatibility": "Windows 11/10/8/7, macOS, Linux, Chrome OS",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-DELL-WIRELESS-MOUSE-2-4-GHZ",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.2). Fochant Dropshipping Price: Rs. 1,256.40. Margin: Rs. 593.60.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "High-Power Waterproof LED Underwater Diving Flashlight & Torch",
    slug: "high-power-waterproof-led-diving-flashlight-torch",
    description: "Heavy-duty waterproof underwater diving torch engineered for deep-sea exploration, scuba diving, night diving, snorkeling, spearfishing, and shrimping. Features ultra-bright high-lumen optical LED emitter with strong underwater beam penetration, double-sealed O-ring waterproof housing, rechargeable battery system with USB charging cable, and a secure safety wrist lanyard.",
    category: "Outdoor & Gadgets",
    sellingPriceLkr: 2850,
    costPriceLkr: 1997,
    sku: "3-DIVING-FLASHLIGHT",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/7c21eff10dc9e163c74d34d6d60bebe0.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/bca4448a985ef91f9284e1bcb92d5299.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/c7d4602c1b011a863c28cc47ad3e23a6.webp",
    ]),
    specs: JSON.stringify({
      "Model": "Professional Underwater Diving Flashlight",
      "Light Source": "High-Lumen High-Intensity LED / COB Emitter",
      "Waterproofing": "Submersible Waterproof Sealed Construction",
      "Applications": "Scuba Diving, Night Dive, Snorkeling, Night Fishing, Shrimping, Marine Safety",
      "Power & Charging": "Rechargeable Battery with Included USB Charging Cable",
      "Safety Accessories": "Includes Heavy-Duty Adjustable Wrist Strap Lanyard",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "19.4 cm (L) x 7.6 cm (Head Width) x 4.0 cm (Body)",
      "Weight": "250 g",
      "Body Material": "Corrosion-Resistant Reinforced ABS & Metal Alloy Reflector",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-DIVING-FLASHLIGHT",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.6). Fochant Dropshipping Price: Rs. 1,996.80. Margin: Rs. 853.20.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Universal 360° Flexible Gooseneck Lazy Bed & Desk Mobile Phone Holder",
    slug: "flexible-gooseneck-lazy-bed-desk-phone-holder",
    description: "Hands-free universal flexible gooseneck lazy bracket phone stand designed for effortless screen viewing in bed, at office desks, or in the kitchen. Features a 75cm heavy-duty bendable magnesium-aluminum alloy core arm, 360-degree rotating ball joint clamp, anti-scratch soft silicone padding, and an ultra-firm base mount clamping securely to tables, headboards, and bedside nightstands.",
    category: "Smartphones",
    sellingPriceLkr: 890,
    costPriceLkr: 586,
    sku: "3-FLEXIBLE-GOOSENECK-MOBILE-PHONE-HOLDER",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/2a314ddc041fd14e77b39f934aad4f91.webp",
      "https://fochant-prod.s3.ap-enjoyable-1.amazonaws.com/testfolder/product_image/394be104d59de18cebe704c3b9ae1816.webp",
      "https://fochant-prod.s3.ap-enjoyable-1.amazonaws.com/testfolder/product_image/be9e2a718496a61a87a69a298bc43efb.webp",
      "https://fochant-prod.s3.ap-enjoyable-1.amazonaws.com/testfolder/product_image/0f19cb469e89b6a279e294a11ea2e223.webp",
    ]),
    specs: JSON.stringify({
      "Model": "Universal Flexible Gooseneck Lazy Bracket",
      "Arm Length / Reach": "75 cm Long Flexible Articulating Arm",
      "Rotation": "360° Swivel Ball Joint Clamp",
      "Base Mount": "Heavy-Duty Surface Clamp with Anti-Slip Pads",
      "Device Protection": "Anti-Scratch Soft Silicone Grip Cushions",
      "Compatible Screen Sizes": "Universal (All Smartphones up to 6.5\" Display)",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "75 cm (Arm Reach) x 12 cm (W) x 60 cm (Extended) | Weight: 300 g",
      "Ideal For": "Bed Headboards, Work Desks, Kitchen Counters, Video Calls & Binge Watching",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-FLEXIBLE-GOOSENECK-MOBILE-PHONE-HOLDER",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.9). Fochant Dropshipping Price: Rs. 585.60. Margin: Rs. 304.40.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Google 30W Power Delivery (PD) Type-C to Type-C Fast Charging Cable (1M)",
    slug: "google-usb-c-to-usb-c-fast-charging-cable-30w",
    description: "High-speed 1-meter Google USB-C to USB-C 30W Power Delivery (PD) & Quick Charge 3.0 fast charging and data transfer cable. Engineered for ultra-fast and safe charging across all Google Pixel smartphones (Pixel 9/8/7/6/5/4/3/7a/8a), Apple iPad Pro/Air, iPhone 15/16 series, MacBooks, Samsung Galaxy devices, and modern Type-C laptops.",
    category: "Chargers & Cables",
    sellingPriceLkr: 950,
    costPriceLkr: 632,
    sku: "3-GOOGLE-USB-C-TO-USB-C-CABLE-30W",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/22f15a8de3175baf6df90ee5ba908318.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/dac792e87773e78eb1e62866a5e64ded.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/e6ca493ef3ec90e2f3754c9ebc5d73ea.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Google",
      "Model": "30W USB-C to USB-C Fast Cable",
      "Cable Length": "1 Meter (100 cm)",
      "Connector Type": "Reversible Type-C to Type-C",
      "Power Output": "30W Power Delivery (PD) & QC 3.0 Support",
      "Data Transfer": "High-Speed Data Sync (Up to 480 Mbps)",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "100 cm (L) x 3 cm (W) x 3 cm (H) | Weight: 30 g",
      "Compatibility": "Google Pixel, MacBook, iPad Pro/Air, iPhone 15/16, Samsung Galaxy, Laptops & PD Chargers",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-GOOGLE-USB-C-TO-USB-C-CABLE-30W",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.2). Fochant Dropshipping Price: Rs. 632.40. Margin: Rs. 317.60.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Heavy-Duty Multi-Plug Surge Protector Extension Board (4 AC + 8 USB + 2 Type-C)",
    slug: "heavy-duty-multi-plug-extension-board-surge-protector",
    description: "All-in-one heavy-duty electrical extension power board and centralized charging station for workstations, home offices, and entertainment setups. Features 4 universal AC power outlets fitting international plug types, 8 high-speed USB-A ports, and 2 USB Type-C Power Delivery ports. Built with a 2-meter heavy-duty cable, fire-retardant casing, and master surge protection overload switch.",
    category: "Computer Accessories",
    sellingPriceLkr: 5200,
    costPriceLkr: 3677,
    sku: "3-HEAVY-DUTY-MULTI-PLUG-EXTENSION-BOARD",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/eea9066d391b51679f5edff0ad45d82c.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/949b516698f886d0b64486f1b23fd62a.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/59164ae37cffe140646562596be1a8f5.webp",
    ]),
    specs: JSON.stringify({
      "AC Outlets": "4 Universal Multi-Socket AC Outlets",
      "USB Ports": "8 USB-A Fast Ports + 2 Type-C (PD) Ports (10 DC Ports Total)",
      "Cable Length": "2.0 Meters (Heavy-Duty Pure Copper Core)",
      "Safety Features": "Master Surge Protection Switch & Overload Auto Cut-off",
      "Casing Material": "High-Grade Fire-Retardant PC Shell",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "24.5 cm (L) x 10.3 cm (W) x 6.5 cm (H)",
      "Weight": "500 g",
      "Ideal For": "Desktop Setups, Home Entertainment, TVs, Monitors, Laptops & Smartphones",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-HEAVY-DUTY-MULTI-PLUG-EXTENSION-BOARD",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.6). Fochant Dropshipping Price: Rs. 3,676.80. Margin: Rs. 1,523.20.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "HP 2.4GHz Universal Ergonomic Optical Wireless Mouse",
    slug: "hp-universal-wireless-mouse-2-4ghz",
    description: "Reliable HP 2.4 GHz wireless optical mouse engineered for smooth and precise computing without cable clutter. Features plug-and-play setup via compact nano USB receiver, responsive optical tracking sensor, ergonomic palm-fit contoured body for long hours of comfortable usage, and universal compatibility with Windows and Mac.",
    category: "Computer Accessories",
    sellingPriceLkr: 1450,
    costPriceLkr: 989,
    sku: "3-HP-UNIVERSAL-WIRELESS-MOUSE",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/da0bab7d9d16b867cdaf0615bb5964a2.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/673e2142fedf5e4d392d4f7389160eb1.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "HP",
      "Connectivity": "2.4 GHz RF Wireless (Plug-and-Play Nano USB Receiver)",
      "Sensor Technology": "High-Precision Optical Sensor Tracking",
      "Buttons": "3 Buttons (Left/Right Click + Smooth Scroll Wheel)",
      "Design": "Ergonomic Ambidextrous Contoured Grip",
      "Power Management": "Smart Battery Saving Mode",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "10 cm (L) x 6 cm (W) x 4 cm (H) | Weight: 110 g",
      "Compatibility": "Universal (Windows 11/10/8/7, macOS, Linux, Chrome OS)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-HP-UNIVERSAL-WIRELESS-MOUSE",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.5). Fochant Dropshipping Price: Rs. 988.80. Margin: Rs. 461.20.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "LBR P4 10000mAh Ultra-Slim 15W Power Bank with 4 Built-In Charging Cables",
    slug: "lbr-p4-10000mah-ultra-slim-power-bank-built-in-cables",
    description: "Ultra-slim 10,000mAh high-density Lithium-Polymer external portable power bank delivering 15W fast charging output. Features 4 built-in integrated output cables (Type-C, Lightning, Micro-USB, and USB-A) eliminating tangled cords, TISI certified safety protections against overheating/overcharging, and airline-approved carry-on compliance for hassle-free travel.",
    category: "Chargers & Cables",
    sellingPriceLkr: 4750,
    costPriceLkr: 3341,
    sku: "3-LBR-P4-POWER-BANK",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/937ac47921dfbbef06ddfbea8b4b47b8.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/63650b4ec6b06a65d57f2b810e2c6227.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/1e9b781a3f73d4b192a53e195f502856.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "LBR",
      "Model": "P4 Portable Power Station",
      "Battery Capacity": "10,000 mAh Lithium-Polymer High-Density Cell",
      "Charging Speed": "15W High-Efficiency Fast Output",
      "Integrated Cables": "4 Built-in Lines (USB-C, Lightning iPhone, Micro-USB, USB-A)",
      "Safety Certifications": "TISI Industrial Compliance (Over-voltage, Short-circuit & Thermal Guard)",
      "Aviation Ready": "100% Airline Flight Approved (Carry-On Safe)",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "14.5 cm (L) x 7.2 cm (W) x 1.8 cm (H) | Weight: 230 g",
      "Compatibility": "Universal (All iPhone & Android smartphones, tablets, earbuds)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-LBR-P4-POWER-BANK",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.7). Fochant Dropshipping Price: Rs. 3,340.80. Margin: Rs. 1,409.20.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "USB 3.0 to Lightning OTG Adapter Converter for iPhone & iPad",
    slug: "usb-3-to-apple-lightning-otg-adapter",
    description: "Ultra-compact USB 3.0 to Apple Lightning On-The-Go (OTG) adapter converter. Enables instant two-way transfer of photos, videos, audio, and documents between your iPhone or iPad and USB pen drives, camera storage cards, keyboards, mice, and external accessories at up to 5Gbps SuperSpeed without requiring third-party apps.",
    category: "Chargers & Cables",
    sellingPriceLkr: 890,
    costPriceLkr: 625,
    sku: "3-LIGHTNING-OTG-ADAPTER",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/48ca7d60df4c50d0868697cdd2647275.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/cd89673b6c521f94cb862d33328c005d.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/34d35cceee87508a5e72f7bf4af7f8d9.webp",
    ]),
    specs: JSON.stringify({
      "Connector In": "Apple 8-Pin Lightning Male Plug",
      "Port Out": "SuperSpeed USB 3.0 Type-A Female Socket",
      "Transfer Rate": "Up to 5 Gbps High-Speed (10x Faster than USB 2.0)",
      "OTG Functionality": "Two-Way Photo/Video/File Sync & Peripheral Support",
      "Supported Peripherals": "Pen Drives, Keyboards, Mice, Digital Cameras, Audio DACs",
      "Housing": "Reinforced Aluminum Alloy Metal Shielding",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "2.0 cm (L) x 2.0 cm (W) x 1.0 cm (H) | Weight: 10 g",
      "Compatibility": "iOS 13+ (Apple iPhone 14/13/12/11/X/8/7/SE, iPad Air, iPad Mini)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-LIGHTNING-OTG-ADAPTER",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.4). Fochant Dropshipping Price: Rs. 625.20. Margin: Rs. 264.80.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Luobr P3 10000mAh Ultra-Slim High-Density Portable Power Bank",
    slug: "luobr-p3-10000mah-ultra-slim-power-bank",
    description: "Sleek and ultra-slim 10,000mAh Lithium-Polymer portable power bank engineered for everyday commuting and travel backup power. Features a textured matte-black anti-slip handheld chassis, dual USB fast output ports plus Type-C connectivity for simultaneous multi-device charging, and safety-certified internal circuitry against overheating and overcharging.",
    category: "Chargers & Cables",
    sellingPriceLkr: 3550,
    costPriceLkr: 2500,
    sku: "3-LUOBR-P3-POWER-BANK",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/a41564281348780ff82f907adca363eb.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/04dcd51febd54427c85e32dc17dda88c.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Luobr",
      "Model": "P3 Slim Series",
      "Battery Capacity": "10,000 mAh High-Density Lithium-Polymer Cell",
      "Charge Cycles": "Provides 2 to 3 Complete Charges for Flagship Smartphones",
      "Output Ports": "Dual USB Fast Outputs + Type-C Input/Output Interface",
      "Design": "Textured Matte Anti-Fingerprint Grip (1.7 cm Slim Profile)",
      "Safety Circuitry": "Integrated Multi-Guard Protection (Overload, Thermal, Short-Circuit)",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "14.5 cm (H) x 7.0 cm (W) x 1.7 cm (L) | Weight: 215 g",
      "Compatibility": "Universal (All iPhone models, Samsung Galaxy, Xiaomi, Pixel, Earbuds)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-LUOBR-P3-POWER-BANK",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.5). Fochant Dropshipping Price: Rs. 2,499.60. Margin: Rs. 1,050.40.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Maxcom 1.5M USB 2.0 High-Speed Printer & Scanner Cable (Type-A to Type-B)",
    slug: "maxcom-usb-2-printer-cable-1-5m",
    description: "High-speed 1.5-meter Maxcom USB 2.0 printer and scanner data cable engineered with standard USB Type-A male to square Type-B male connectors. Built with premium pure copper wiring, dual foil-and-braid EMI shielding to prevent signal loss, and up to 480 Mbps high-speed data transfer. Universal plug-and-play compatibility with HP, Canon, Epson, and Brother printers, scanners, audio interfaces, and digital pianos.",
    category: "Computer Accessories",
    sellingPriceLkr: 650,
    costPriceLkr: 416,
    sku: "3-MAXCOM-USB-PRINTER-CABLE",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/46dd940a3ab4ff3dd8a2f94ec30dbbcb.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/367222e24f4192ba0719ee13c1627f39.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/43922e35cb50b0483aa54e4e3c5d2c72.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Maxcom",
      "Model": "High-Speed USB 2.0 Printer Cable",
      "Cable Length": "1.5 Meters (Approx. 5 Feet / 150 cm)",
      "Connectors": "Standard USB Type-A Male to Square USB Type-B Male",
      "Data Transfer Rate": "High-Speed up to 480 Mbps (Backwards compatible with USB 1.1)",
      "Shielding & Core": "Pure Copper Wires with Dual Foil & Braid EMI Interference Shielding",
      "Jacket Material": "Heavy-Duty Flexible PVC with Molded Strain Relief",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "150 cm (Length) x 0.45 cm (Cable Diameter) | Weight: 65 g",
      "Compatibility": "Universal (HP, Canon, Epson, Brother, Lexmark Printers, Scanners, Audio DACs, MIDI Keyboards)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-MAXCOM-USB-PRINTER-CABLE",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.4). Fochant Dropshipping Price: Rs. 416.40. Margin: Rs. 233.60.",
    isFeatured: true,
    isBestSeller: false,
  },
  {
    title: "Motorcycle & Scooter Side Mirror 360° Rotatable Mobile Phone Holder Mount",
    slug: "motorcycle-side-mirror-360-phone-holder-mount",
    description: "Heavy-duty motorcycle and scooter phone mount bracket designed specifically for quick attachment under the rearview side mirror stem. Features 360-degree omnidirectional rotation for seamless GPS navigation in portrait or landscape orientation, firm multi-point gripping claws with anti-slip silicone cushions, and shock-resistant construction for bumpy roads.",
    category: "Smartphones",
    sellingPriceLkr: 1250,
    costPriceLkr: 854,
    sku: "3-MOBILE-PHONE-HOLDER-SIDE-MIRROR",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/7495e80d0e43bf3eab7468eeccdd20e6.webp",
    ]),
    specs: JSON.stringify({
      "Model": "2-in-1 Side Mirror Motorcycle Phone Mount",
      "Mounting Position": "Rearview Side Mirror Stem Bolt",
      "Rotation": "360° Full Swivel Ball Joint (Portrait & Landscape)",
      "Clamp Mechanism": "Firm Multi-Point Dual Wing Clamps with Quick Release",
      "Shock Protection": "Anti-Vibration Rubberized Backplate & Silicone Grips",
      "Compatible Sizes": "Universal (Fits 4.5\" to 7.0\" Smartphones)",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "15 cm (H) x 11 cm (W) x 7 cm (L) | Weight: 200 g",
      "Compatibility": "Motorcycles, Scooters, E-Bikes, Mopeds",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-MOBILE-PHONE-HOLDER-SIDE-MIRROR",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.2). Fochant Dropshipping Price: Rs. 854.40. Margin: Rs. 395.60.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "LB-Link 150Mbps Mini Nano Wireless USB Wi-Fi Adapter Dongle (802.11n)",
    slug: "lb-link-150m-nano-wireless-usb-wifi-adapter",
    description: "Ultra-compact LB-Link 150Mbps mini nano wireless USB Wi-Fi dongle receiver. Upgrades desktop PCs or laptops to fast 2.4GHz wireless internet (IEEE 802.11b/g/n) with speeds up to 150 Mbps. Engineered with a flush nano profile that stays securely plugged in without snagging during travel or blocking adjacent USB ports. Supports advanced WEP, WPA-PSK, and WPA2-PSK network security.",
    category: "Computer Accessories",
    sellingPriceLkr: 1350,
    costPriceLkr: 894,
    sku: "3-NANO-WIRELESS-USB-ADAPTER",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/a828a3c952d42ad8ef1175775d430ed2.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/9eb7d51cae6d1ee201be7b3299bccf3e.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/b6880cd840b77f7813b92f5c4589964e.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "LB-Link",
      "Model": "150M Nano Wireless USB Adapter (BL-WN151)",
      "Wireless Standard": "IEEE 802.11b / 802.11g / 802.11n",
      "Frequency Band": "2.4 GHz Stable Frequency",
      "Transfer Speed": "Up to 150 Mbps High-Speed Wi-Fi",
      "Interface": "Standard USB 2.0 / USB 3.0 Port Compatible",
      "Form Factor": "Ultra-Compact Flush Nano Size (Leave-in Dongle)",
      "Security Encryption": "64/128-bit WEP, WPA-PSK, WPA2-PSK Protocols",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "1.93 cm (L) x 1.45 cm (W) x 0.65 cm (H) | Weight: 3 g",
      "Compatibility": "Windows 11/10/8/7/XP, macOS, Linux, Desktop Towers & Laptops",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-NANO-WIRELESS-USB-ADAPTER",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.1). Fochant Dropshipping Price: Rs. 894.00. Margin: Rs. 456.00.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Universal Outdoor CCTV Security Camera Weather Shield & Rain/Sun Visor Cover",
    slug: "universal-outdoor-cctv-security-camera-weather-shield-cover",
    description: "Heavy-duty universal outdoor CCTV security camera protective roof cover. Formed from UV-resistant high-impact ABS plastic to provide comprehensive all-weather defense against torrential monsoon rains, harsh sunlight, lens glare, dust accumulation, and water streaks. Features an extended sunshade visor that prevents overexposed surveillance footage and fits all standard Bullet, Dome, and PTZ security cameras.",
    category: "Outdoor & Gadgets",
    sellingPriceLkr: 1190,
    costPriceLkr: 786,
    sku: "3-OUTDOOR-CCTV-CAMERA-COVER",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/08f3cddd423922501b0f593821f28915.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/ec4b9ab9865502f5f0b6a8ec0c09aed4.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/fb50432aeff8cb64dceec6db8bae517a.webp",
    ]),
    specs: JSON.stringify({
      "Model": "Universal CCTV Weather Proof Protective Shield",
      "Material": "Heavy-Duty UV-Resistant Reinforced ABS Plastic",
      "Weather Defense": "Heavy Rain, Intense Sun Glare, Windblown Dust, Snow & Thermal Heat",
      "Optics Enhancement": "Extended Sun Visor Prevents Lens Flare & Overexposure",
      "Installation": "Overhead Wall Mount with Pre-Drilled Screw Holes",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "29.0 cm (Length) x 20.5 cm (Width) x 20.5 cm (Height)",
      "Weight": "190 g",
      "Compatibility": "Universal (Hikvision, Dahua, Ezviz, Imou, TP-Link, Xiaomi Bullet/Dome/PTZ Cameras)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-OUTDOOR-CCTV-CAMERA-COVER",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.6). Fochant Dropshipping Price: Rs. 786.00. Margin: Rs. 404.00.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "P9 Wireless Bluetooth 5.3 Over-Ear Stereo Headphones with Built-in Mic",
    slug: "p9-wireless-bluetooth-stereo-headphones",
    description: "Stylish P9 over-ear wireless Bluetooth 5.3 stereo headphones engineered with powerful 40mm dynamic acoustic drivers delivering rich punchy bass and crystal-clear treble. Features a comfortable breathable memory foam ear cushion design with flexible mesh canopy headband, built-in HD microphone for hands-free crystal voice calls, responsive on-ear controls, and up to 6 hours continuous playtime with 120 hours standby on a single charge.",
    category: "Audio",
    sellingPriceLkr: 1650,
    costPriceLkr: 1123,
    sku: "3-P9-WIRELESS-BLUETOOTH-HEADPHONE",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/6c8635d566bc812f300fe99d03c08aff.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/6c03bad9deeb3316c9f87629c78b0ff2.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/27dddc728698fc0edd3abb6e2fc4a400.webp",
    ]),
    specs: JSON.stringify({
      "Model": "P9 Wireless Stereo Headset",
      "Bluetooth Version": "Bluetooth 5.3 High-Efficiency Audio",
      "Driver Unit": "40 mm High-Definition Dynamic Bass Drivers",
      "Battery Capacity": "400 mAh Long-Life Rechargeable Battery",
      "Battery Life": "5–6 Hours Playback / Talk Time | 120 Hours Standby",
      "Charging Time": "Approx. 2 Hours",
      "Microphone": "Integrated HD Hands-Free Call Microphone",
      "Ergonomics": "Soft Memory Foam Earcups with Adjustable Headband",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "25 cm (L) x 20 cm (W) x 20 cm (H)",
      "Weight": "250 g",
      "Compatibility": "Universal (iPhone, Samsung, Xiaomi, Android, PC, Laptops, Smart TVs)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-P9-WIRELESS-BLUETOOTH-HEADPHONE",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.2). Fochant Dropshipping Price: Rs. 1,123.20. Margin: Rs. 526.80.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Plokama PK-79 Rechargeable 64-LED Video Fill Light with Laptop Screen Clip",
    slug: "plokama-pk-79-led-video-fill-light-clip",
    description: "Ultra-portable pocket-sized Plokama PK-79 64-LED video fill light engineered for Zoom video conferences, remote work, live streaming, vlogging, and mobile content creation. Features professional 95+ high Color Rendering Index (CRI) for natural skin tones, dual color temperature (3200K warm to 5600K daylight), 10 brightness dimming levels, heavy-duty padded laptop screen clip, universal 1/4\" tripod mount thread, and built-in rechargeable battery.",
    category: "Smartphones",
    sellingPriceLkr: 1490,
    costPriceLkr: 1042,
    sku: "3-PLOKAMA-PK-79-LED-VIDEO-LIGHT",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/0aafa417e887adde89be52a1ed8cb09b.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/76207f8066d778267923f36b4e6914e7.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/956cc4f6d418ce3a40b326c2e8cb768c.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/99fe2169f45e8154a8b936da0201746d.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Plokama",
      "Model": "PK-79 LED Video Fill Light",
      "LED Quantity": "64 Advanced High-Lumen LED Beads",
      "Color Rendering Index": "CRI ≥ 95+ (True Natural Color Accuracy)",
      "Color Temperature": "3200K (Warm Sunset) – 5600K (Cool Daylight)",
      "Dimming Controls": "10-Level Tactile Stepped Brightness Adjustment",
      "Dual Mounting": "Padded Anti-Scratch Laptop/Phone Clip + 1/4\" Universal Screw Thread",
      "Power & Battery": "Built-in Rechargeable Lithium Battery (USB Rechargeable)",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "8.5 cm (L) x 7.0 cm (W) x 2.5 cm (H)",
      "Weight": "34 g (Ultra-Lightweight & Pocket-Sized)",
      "Compatibility": "Laptops, MacBooks, Tablets, iPhone, Android Smartphones, DSLRs & Tripods",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-PLOKAMA-PK-79-LED-VIDEO-LIGHT",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 5.0). Fochant Dropshipping Price: Rs. 1,041.60. Margin: Rs. 448.40.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Plokama U20 Pro Clip-On LED + RGB Fill Light with Selfie Mirror & 180° Swivel",
    slug: "plokama-u20-pro-led-rgb-fill-light",
    description: "Ultra-portable clip-on LED and RGB content creation fill light designed for smartphones, tablets, and laptops. Features 10 vibrant RGB custom color spectrums, 3 professional bi-color temperature modes (warm, soft, cool), 180-degree physical rotation for front/rear camera lighting, integrated wide-view convex selfie framing mirror, and built-in 300mAh rechargeable battery delivering up to 180 minutes of continuous flicker-free illumination via USB Type-C fast charging.",
    category: "Smartphones",
    sellingPriceLkr: 1490,
    costPriceLkr: 1042,
    sku: "3-PLOKAMA-U20-PRO-LED-RGB-FILL-LIGHT",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/395b29486f5ebf37378deec967a39250.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/377face5be93653a9f82fb89fb81c12f.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/28a23008ee18cd5f7733aa09a2720591.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/746ef2e3292872b69d221ef709a87509.webp",
    ]),
    specs: JSON.stringify({
      "Brand": "Plokama",
      "Model": "U20 Pro LED+RGB Fill Light",
      "Lighting Modes": "3 Bi-Color Modes (Warm, Soft, Cool) + 10 Vibrant RGB Colors",
      "Brightness & Control": "Multi-Level Stepped Dimming Adjustments",
      "Rearview Mirror": "Built-in Convex Framing Selfie & Touch-up Mirror",
      "Rotation": "180° Articulating Swivel (Illuminates Front & Rear Cameras)",
      "Battery Capacity": "300 mAh Rechargeable Lithium Battery",
      "Runtime": "Up to 180 Minutes (3 Hours) Continuous Flicker-Free Light",
      "Charging Port": "USB Type-C Fast Charging",
      "Mounting Type": "Anti-Scratch Universal Screen Clip",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "9.9 cm (H) x 6.8 cm (W) x 1.37 cm (Thickness)",
      "Weight": "51 g (Ultra-Lightweight & Pocket-Sized)",
      "Compatibility": "Universal (iPhone, Android Smartphones, iPads, Tablets, Laptops & MacBooks)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-PLOKAMA-U20-PRO-LED-RGB-FILL-LIGHT",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.9). Fochant Dropshipping Price: Rs. 1,041.60. Margin: Rs. 448.40.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "USB to DC 9V/12V Step-Up Power Boost Cable for Wi-Fi Routers & Modems (1M)",
    slug: "usb-to-dc-step-up-power-boost-cable-router",
    description: "Plug-and-play 1-meter USB to DC step-up voltage converter power boost cable. Converts standard 5V DC input from any portable power bank, laptop, or USB adapter into a stable 9V or 12V DC output (up to 1A). Equipped with a standard USB-A input and universal 5.5mm x 2.1mm DC barrel connector to power Wi-Fi routers, 4G LTE modems, SLT Fibre units, CCTV cameras, and mini LED lights continuously during power cuts.",
    category: "Chargers & Cables",
    sellingPriceLkr: 850,
    costPriceLkr: 571,
    sku: "3-POWER-BOOST-CABLE",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/949f251ae1a00572a8b1aa84d4718145.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/0793ba207c8e3ebad69fc3b35948be07.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/39de9b3ddae65145f04aa7f650f3bfb7.webp",
    ]),
    specs: JSON.stringify({
      "Model": "USB 5V to DC 9V/12V Step-Up Boost Line",
      "Input Interface": "Standard USB Type-A Male (5V DC Input)",
      "Output Interface": "Universal 5.5mm x 2.1mm DC Barrel Jack Plug",
      "Voltage Conversion": "Steps Up 5V DC to Stable 9V / 12V DC (Up to 1A Max)",
      "Cable Length": "1.0 Meter (100 cm)",
      "Internal Circuitry": "Molded Smart Step-Up PCB with Over-Current & Thermal Protection",
      "Blackout Backup": "Run Internet Routers directly from Power Banks during power outages",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "100 cm (Length) x 0.4 cm (Diameter)",
      "Weight": "35 g (Pocket-Sized & Ultra-Lightweight)",
      "Compatibility": "SLT Fibre Routers, Dialog/Mobitel 4G LTE Modems, CCTV Cameras, Mini Fans & LED Strips",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-POWER-BOOST-CABLE",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.5). Fochant Dropshipping Price: Rs. 571.20. Margin: Rs. 278.80.",
    isFeatured: true,
    isBestSeller: true,
  },
  {
    title: "Universal 360° Rotatable Metallic Finger Ring Holder & Kickstand",
    slug: "stylish-mobile-ring-holder-stand",
    description: "Ultra-slim universal metallic finger ring holder and desktop kickstand for smartphones. Features a 360-degree omnidirectional rotatable base and 180-degree folding ring hinge for customizable viewing angles in portrait or landscape mode. Built with high-grade durable metal alloy, strong non-marking adhesive backing, and an ergonomic anti-drop finger grip to ensure secure one-handed phone operation.",
    category: "Smartphones",
    sellingPriceLkr: 450,
    costPriceLkr: 276,
    sku: "3-STYLISH-MOBILE-RING",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/5878e8348362e5b56554f816a4c2e128.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/8456c0149fc9ee9e27c2ec030e300dc7.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/f8ed42dc4b31943b7b7a8bd6d93f9d16.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/3e1cb9424b308df8a4917ab228be7fb7.webp",
    ]),
    specs: JSON.stringify({
      "Model": "Stylish Universal Mobile Finger Ring Grip",
      "Rotation & Flip": "360° Base Rotation + 180° Vertical Flip Hinge",
      "Material": "Reinforced Polished Zinc Alloy Metal Body",
      "Functionality": "Anti-Drop Finger Grip, Desktop Kickstand & Car Mount Ready",
      "Mounting Adhesive": "Ultra-Strong Pressure Adhesive (Residue-Free)",
      "Folded Thickness": "Ultra-Slim 0.7 cm Flat Profile",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "3.5 cm (L) x 3.5 cm (W) x 0.7 cm (H)",
      "Weight": "10 g (Ultra-Lightweight)",
      "Compatibility": "Universal (All iPhone models, Android smartphones & back cases)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-STYLISH-MOBILE-RING",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.1). Fochant Dropshipping Price: Rs. 276.00. Margin: Rs. 174.00.",
    isFeatured: false,
    isBestSeller: true,
  },
  {
    title: "Cyberpunk 20000mAh Transparent Fast Charging Power Bank with 4 Built-In Cables",
    slug: "transparent-20000mah-fast-charging-power-bank",
    description: "Futuristic 20,000mAh transparent mecha cyberpunk fast-charging external power bank. Features an industrial see-through front casing displaying the internal motherboard circuits, 4 built-in ribbon cables (Type-C, Apple Lightning, Micro-USB, and USB-A) for tangle-free multi-device charging, a smart circular digital LED battery percentage display (0–100%), and a heavy-duty yellow carry loop strap for travel and daily commute.",
    category: "Chargers & Cables",
    sellingPriceLkr: 4950,
    costPriceLkr: 3475,
    sku: "3-TRANSPARENT-20000MAH-POWER-BANK",
    stock: 133,
    images: JSON.stringify([
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/ba5eb9298ab38fb7b0b3886e82e38e72.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/e37c3a2c0324476b282f6e4f8e2c63ee.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/38a401a8854310cbcd080d7538ee15c4.webp",
      "https://fochant-prod.s3.ap-southeast-1.amazonaws.com/testfolder/product_image/17ea521fe4d6d5d5ca9d6d72134b68b5.webp",
    ]),
    specs: JSON.stringify({
      "Model": "Transparent Cyberpunk 20000mAh Power Bank",
      "Battery Capacity": "20,000 mAh High-Density Lithium-Polymer",
      "Aesthetic": "Industrial Cyberpunk Transparent Front (Visible PCB & Components)",
      "Built-in Cables": "4 Multi-Output Lines (USB-C, Lightning iPhone, Micro-USB, USB-A)",
      "Digital Display": "Circular Smart LED Battery Percentage Indicator (0-100%)",
      "Simultaneous Charging": "Charges up to 4–5 devices simultaneously",
      "Carry Strap": "Heavy-Duty Yellow Travel Lanyard Loop",
      "Protection": "Multi-Layer Smart Protection (Overcharge, Overheating, Short-Circuit)",
      "Warranty": "Checking Warranty (3 Days)",
      "Dimensions": "13.5 cm (L) x 6.8 cm (W) x 2.5 cm (H)",
      "Weight": "420 g",
      "Compatibility": "Universal (All iPhone models, Samsung Galaxy, Xiaomi, Pixel, Tablets, Earbuds)",
    }),
    supplierLink: "https://fochantdropshipping.com/seller-products-detail/3-TRANSPARENT-20000MAH-POWER-BANK",
    supplierNotes: "Supplier: Aryans Pvt Ltd (Rating: 4.0). Fochant Dropshipping Price: Rs. 3,475.20. Margin: Rs. 1,474.80.",
    isFeatured: true,
    isBestSeller: true,
  },
];

async function main() {
  console.log("Cleaning all mock data and seeding GizmoTek.lk database with real products...");

  // Delete all existing items, orders, reviews, and products
  await prisma.orderItem.deleteMany({});
  await prisma.order.deleteMany({});
  try {
    await prisma.review.deleteMany({});
  } catch (err) {}
  await prisma.product.deleteMany({});

  console.log("Database cleared.");

  // Insert real products
  for (const item of realProducts) {
    await prisma.product.create({
      data: item,
    });
  }

  console.log(`Database successfully initialized with ${realProducts.length} real products!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
